### ISSUE TITLE
Executing dellemc_configure_idrac_users twice fails the second attempt

### ISSUE THREAD

**Issue by mikeletux** [dell/dellemc-openmanage-ansible-modules#100]
Hello there,

I've been experiencing issues running the dellemc_configure_idrac_users module.
Turns out that if you use it for creating a user that does not exist, it works, but if you run the exact same thing twice, it gives an error. My conclusion on this is that the module is not idempotent.
I use the parameter "action" with "create" value.

- name: Create the iDRAC users
    dellemc_configure_idrac_users: 
      idrac_ip:  "{{ idrac_ip }}"
      idrac_user:  "{{ idrac_user }}"
      idrac_password:  "{{ idrac_password }}"
      share_name:      "{{ share_name }}"
      share_mnt:       "{{ share_mnt }}"
      action: "create" 
      user_name: "{{ user }}"
      user_password: "{{ password }}" 
      privilege_users: "Administrator" 

Can you please check this?
Many thanks.

/Miguel

**Comment by thizmo** [comment]
I see the same problem here.
It fails on the second run. Then i am not able to log in any more.

**Comment by jagadeeshnv** [comment]
Thank you for reporting @mikeletux and @thizmo. We will look into it and do the needful

**Comment by tsquillario** [comment]
The dellemc_configure_idrac_users module does not adhere to Ansible best practices. It should use a 'state' parameter instead of 'action' and accept 'present' or 'absent'. Then it should detect if this users already exists and modify it accordingly.

**Comment by tsquillario** [comment]
This module also needs rewritten to remove the dependency on the liaison share. I set 'share_name' to /tmp and I get "Unable to export scp, exception occurred"

**Comment by jagadeeshnv** [comment]
@tsquillario We have addressed this issue with the new module "idrac_user" Kindly verify and let us know

**Comment by jagadeeshnv** [comment]
@tsquillario Can you please verify and close this issue?

**Comment by jagadeeshnv** [comment]
@tsquillario This has been fixed module 'idrac_user' as stated above. Hence closing this issue. Thank You
