### ISSUE TITLE
Feature Request: idrac_server_config_profile local file import

### ISSUE THREAD

**Issue by tsquillario** [dell/dellemc-openmanage-ansible-modules#111]
I would like to Import a local XML file in the ansible role directory, no share. Users will expect this functionality as ansible makes heavy use of files and templates. This would allow you to manage the XML files in source control as well. Eventually I would like to use variables to dynamically generate XML files using templates.

Local file import is currently possible via Redfish https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/ImportSystemConfigurationLocalFilenameREDFISH.py

If the plan is to stick with omsdk I think a function will need to be added to
https://github.com/dell/omsdk/blob/devel/omdrivers/lifecycle/iDRAC/iDRACConfig.py

**Comment by jagadeeshnv** [comment]
@tsquillario idrac_server_config_profile supports import and export locally. Can you confirm the exact scenario

**Comment by tsquillario** [comment]
Sorry I guess I didn't test this well enough. I can confirm it works as expected! Thanks.
