### ISSUE TITLE
dellemc_configure_idrac_users is unreliable - errors

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#113]
Hello,  i spent last few developing code to configure idrac using modules. Part of it is reset of root password. 
I have ran this module many times and 7 out 10 i get always the same error bellow. My approach is to create temp_root, user temp_root to change root and delete temp_root.
Is there anything you can do about it to fix it ?
Error usually comes before the module configuration export part is completed.

{
    "changed": false,
    "msg": {
        "StatusCode": 503,
        "Status": "Failed",
        "Data": {
            "Status": "Failed",
            "Message": "returned status code doesn't match with the expected success code",
            "StatusCode": 503
        },
        "error": {
            "error": {
                "@Message.ExtendedInfo": [
                    {
                        "Message": "A job operation is already running. Retry the operation after the existing job is completed.",
                        "MessageArgs": [],
                        "MessageArgs@odata.count": 0,
                        "MessageId": "IDRAC.2.1.RAC0679",
                        "RelatedProperties": [],
                        "RelatedProperties@odata.count": 0,
                        "Resolution": "Wait until the running job is completed or delete the scheduled job and retry the operation.",
                        "Severity": "Warning"
                    }
                ],
                "code": "Base.1.5.GeneralError",
                "message": "A general error has occurred. See ExtendedInfo for more information"
            }
        },
        "retval": true,
        "Message": "none",
        "file": "/tmp/idrac/scp_uxdkf73.xml1"
    },
    "invocation": {
        "module_args": {
            "idrac_ip": "10.10.10.10",
            "idrac_user": "temp_root",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "share_name": "/tmp/idrac",
            "share_mnt": "/mnt",
            "action": "modify",
            "user_name": "root",
            "user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "privilege_users": "Administrator",
            "ipmilanprivilege_users": "Administrator",
            "ipmiserialprivilege_users": "Administrator",
            "enable_users": "Enabled",
            "solenable_users": "Enabled",
            "protocolenable_users": "Enabled",
            "authenticationprotocol_users": "SHA",
            "privacyprotocol_users": "AES",
            "idrac_port": 443,
            "share_password": null,
            "share_user": null
        }
    },
    "_ansible_no_log": false
}

**Comment by ThierryBesancon** [comment]
Hello.

I encounter errors too when using `dellemc_configure_idrac_users`. OMAM 2.0.14, iDRAC 4.20.20.20.

On a first run, i create a user. Either using OMAM or using the web interface. Not important.

Then with OMAM `dellemc_configure_idrac_users` i delete that user. No error. On the same playbook i continue with creating the same user again (after all, it was removed so i should be able to recreate it -- as long as creation of a user is not idempotent in OMAM, i could not think of other way to ensure a user is created than delete it then recreate it, as a non existent user removal does not fail). It fails with `A job operation is already running. Retry the operation after the existing job is completed.`. Though, if i check the job queue with the web interface, i find no running job. Then i am stuck as i always get errors about running job. I need to soft reset the iDRAC with `dellemc_idrac_reset`.

So there might be an error in the processing of user management.

Of course, you can get to idempotence by creating user using XML user part of a SCP. But is this solid as rock in the long term?

Thanks in advance for analysis this bug.

**Comment by jagadeeshnv** [comment]
@markatdxb We have addressed this issue with the new module "idrac_user" Kindly verify and let us know

**Comment by jagadeeshnv** [comment]
@markatdxb Can you please verify and close this issue?

**Comment by markatdxb** [comment]
@jagadeeshnv  - we will run tests within this week and provide feedback

**Comment by markatdxb** [comment]
Im closing this - seems to be working as expected now. Thanks

**Comment by zaiguiw** [comment]
Which version of the module this issue was fixed in? I seem to still experience this same issue:

"Message": "A job operation is already running. Retry the operation after the existing job is completed.", "MessageArgs": [], "MessageArgs@odata.count": 0, "MessageId": "IDRAC.2.5.RAC0679", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "Wait until the running job is completed or delete the scheduled job and retry the operation.", "Severity": "Warning"}], "code": "Base.1.8.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}

**Comment by zaiguiw** [comment]
I am doing user operations in a loop. Adding a pause of 2-3s between the loops through loop_control seems to help fix the issue mostly.
