### ISSUE TITLE
idrac_firmware - error when using https://downloads.dell.com

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#117]
Hello, been testing this module extensively over the last few days. 
I'm getting following errors when trying to use https://downloads.dell.com
Need to mentioned that in our environment we need to use proxy for internet access. 
Ansible is configured for proxy internet access.

{
    "msg": "Failed to update firmware.",
    "update_status": {
        "Data": {
            "InstallFromRepository_OUTPUT": {
                "Message": "The input value entered for the parameter ShareType is invalid",
                "MessageID": "SUP026",
                "ReturnValue": "2"
            }
        },
        "Status": "Error",
        "Message": "The input value entered for the parameter ShareType is invalid",
        "MessageID": "SUP026",
        "Return": "Error",
        "retval": false,
        "file": "https://152.199.20.130/Catalog.xml",
        "job_details": {
            "Data": {
                "GetRepoBasedUpdateList_OUTPUT": {
                    "Message": "The GetRepoBasedUpdateList method did not complete successfully",
                    "MessageID": "SUP028",
                    "ReturnValue": "2"
                }
            },
            "Status": "Error",
            "Message": "The GetRepoBasedUpdateList method did not complete successfully",
            "MessageID": "SUP028",
            "Return": "Error",
            "retval": true
        }
    },
    "invocation": {
        "module_args": {
            "idrac_ip": "10.10.10.10",
            "idrac_user": "root",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "share_name": "https://downloads.dell.com",
            "reboot": true,
            "job_wait": true,
            "idrac_port": 443,
            "catalog_file_name": "Catalog.xml",
            "ignore_cert_warning": true,
            "apply_update": true,
            "share_user": null,
            "share_password": null,
            "share_mnt": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

**Comment by Mixer9** [comment]
How was this resolved???
