### ISSUE TITLE
idrac_firmware allow downgrade option

### ISSUE THREAD

**Issue by tsquillario** [dell/dellemc-openmanage-ansible-modules#119]
If you run against a DRM repo with older firmware it will downgrade the firmware. I think we should have an option to allow that or not because it can be useful in certain scenarios.

**Comment by anupamaloke** [comment]
@tsquillario, thanks for providing this feedback. I have added this requirement to our backlog.

**Comment by anupamaloke** [comment]
@tsquillario, thanks for providing this feedback. I will have this added to backlog for next release. please stay tuned for update
