### ISSUE TITLE
Issue #49: KeyError: idrac_password

### ISSUE THREAD

**Issue by GreyGnome** [dell/dellemc-openmanage-ansible-modules#121]
As I mention at the end of issue 49:

This is still an issue for me with the latest dellemc-openmanage-ansible-modules (downloaded today 2020 05 18- version 2.0.12) and with ansible 2.9.1. This time, I needed to edit line 33, in /usr/lib/python2.7/site-packages/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py and make it look like this:

self.idrac_pwd = module_params['idrac_pwd']

If I try to use "idrac_password" in my Ansible YML file, the system will complain that it's an unsupported parameter, and I need to use idrac_pwd:

Supported parameters include: command, end_host_power_state, export_format, export_use, idrac_ip, idrac_port, idrac_pwd

**Comment by jagadeeshnv** [comment]
Hi @GreyGnome 
Looks like the old version of dellemc-openmanage-ansible-modules is still in your system. Do you have both Python-2 and Python-3 in you system. Our code has been changed in 2.0.1 for this issue
See this. https://github.com/dell/dellemc-openmanage-ansible-modules/blob/7a2411efdc76050e0345b3188bbca8b60849dab3/utils/dellemc_idrac.py#L33

**Comment by GreyGnome** [comment]
You are correct. I performed a fresh install on a freshly-built RHEL 7.4 system and it worked great. Thanks.
