### ISSUE TITLE
idrac_firmware - add proxy option

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#130]
hi, 
any chance you could add option to specify http proxy as part of the idrac_firmware module ? 
We need it in order to access donwloads.dell.com 
thanks

**Comment by benfab** [comment]
We are also hitting this limitation, so very keen on having this option avaible as part of the idrac_firmware module.

**Comment by sdx23** [comment]
We're as well missing that feature and would be glad to see it available.

**Comment by anupamaloke** [comment]
Closed by #458
