### ISSUE TITLE
Examples are just json return output

### ISSUE THREAD

**Issue by dmc5179** [dell/dellemc-openmanage-ansible-modules#133]
All of the sample files that I've looked at in this repository are not sample yaml for ansible. They are the json output that is returned when a module is run. This is not helpful or useful at all. Every single file in here is json output....

https://github.com/dell/dellemc-openmanage-ansible-modules/tree/devel/samples/idrac

**Comment by jagadeeshnv** [comment]
Hi @dmc5179 
please look into the examples https://github.com/dell/dellemc-openmanage-ansible-modules/tree/devel/examples for yaml

**Comment by dmc5179** [comment]
@jagadeeshnv Yes, I noticed a day or so after I submitted the issue that there is an examples and a samples folder. Examples has the example yaml for the ansible tasks. Samples has json output. What exactly is the json output for? I certainly don't see this json output in ansible unless maybe there is an issue with the tasks.

**Comment by jagadeeshnv** [comment]
@dmc5179 With verbose mode  you can see detailed output. This is just for reference

**Comment by ThierryBesancon** [comment]
It is useful. With the description of the dict you get in the answer (see `md` file), you can decide by yourself if your task encountered a real failure or not, by your own definition of a failure (see #103 where the answer dict circumvents a false failure).

**Comment by jagadeeshnv** [comment]
@dmc5179 We have renamed the directory for better clarity. Please check
