### ISSUE TITLE
ome_firmware_catalog and ome_firmware_baseline not idempotent

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#146]
If the specified catalog or baseline is not present, the commands run correctly.  If a catalog already exists with the same name, an error is thrown, which is contrary to the standard Ansible use case.

 FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to create or update the catalog because a repository with the same name already exists.", "MessageArgs": [], "MessageId": "CUPD3064", "RelatedProperties": [], "Resolution": "Enter a different name and retry the operation.", "Severity": "Critical"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: Bad Request"}

FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to create or update the baseline because a baseline with the same name already exists.", "MessageArgs": [], "MessageId": "CUPD3098", "RelatedProperties": [], "Resolution": "Enter a unique baseline name and retry the operation.", "Severity": "Critical"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: Bad Request"}

**Comment by MallocArray** [comment]
Still present in 2.1.3

**Comment by jagadeeshnv** [comment]
@MallocArray OME 3.0 had support for creation only, hence such behaviour. With latest OME we have support for modification of catalog and baseline. Will enhance the module with modification and delete support soon

**Comment by jagadeeshnv** [comment]
@MallocArray With the latest release this feature is added to the modules.
