### ISSUE TITLE
OS Deployment Using HTTP,FTP Share

### ISSUE THREAD

**Issue by elikkayaemircan** [dell/dellemc-openmanage-ansible-modules#153]
Current modules have oppurtunity to deploy OS using NFS and CIFS shares, but HTTP and FTP could be helpfull, too. Issue #141 did not mention these protocols. Also HTTP, FTP is available on firmware installations. Any suggestion to implement this feature?

**Comment by sachin-apa** [comment]
@elikkayaemircan do please try the new role `idrac_os_deployment` supports http/https using virtual deployment more details [here ](https://github.com/dell/dellemc-openmanage-ansible-modules/tree/collections/roles/idrac_os_deployment)
