### ISSUE TITLE
idrac_firmware: AttributeError: 'OpenURLResponse' object has no attribute 'code

### ISSUE THREAD

**Issue by MikeDaSystemAdmin** [dell/dellemc-openmanage-ansible-modules#156]
Playbook is below:

---
- hosts: localhost
  connection: local
  name: Update Firmware Inventory
  gather_facts: False

  tasks:
  - name: Update firmware from repository on a HTTP/HTTP/FTP repository
    idrac_firmware:
       idrac_ip: "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password: "{{ idrac_password}}"
       share_name: "https://downloads.dell.com"
       reboot: True
       job_wait: True
       apply_update: True
       ignore_cert_warning: True

When I run this, the Job Queue does get the job, and the update does occur.  however the ansible play fails with this error:

AttributeError: 'OpenURLResponse' object has no attribute 'code'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600979353.62-16765-228947460323250/AnsiballZ_idrac_firmware.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600979353.62-16765-228947460323250/AnsiballZ_idrac_firmware.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600979353.62-16765-228947460323250/AnsiballZ_idrac_firmware.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.remote_management.dellemc.idrac_firmware', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_idrac_firmware_payload_noeskdbl/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 403, in <module>\n  File \"/tmp/ansible_idrac_firmware_payload_noeskdbl/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 391, in main\n  File \"/tmp/ansible_idrac_firmware_payload_noeskdbl/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 320, in update_firmware\n  File \"/tmp/ansible_idrac_firmware_payload_noeskdbl/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 263, in update_firmware_url\n  File \"/tmp/ansible_idrac_firmware_payload_noeskdbl/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 235, in get_jobid\nAttributeError: 'OpenURLResponse' object has no attribute 'code'\n",

**Comment by anupamaloke** [comment]
@MikeDaSystemAdmin, what is the server model and the iDRAC firmware version?

**Comment by apaqd** [comment]
I've got the same issue. Server: PowerEdge R740xd2 ; IDRAC FW: 4.22.00.53

**Comment by MikeDaSystemAdmin** [comment]
I am connecting to a PowerEdge R440
  The drac is 4.22.00.53 / 4.22.00.00 (Both versions cause the same error)

I have been able to replicate this on another machine with OMSDK installed, and both machines are using OMSDK Version 2.1.2

**Comment by MikeDaSystemAdmin** [comment]
As an update, I setup a Venv (My above examples were doing it straight from ansible).  My Venv is running ansible 2.9.13, and I get the same error.

**Comment by jagadeeshnv** [comment]
@MikeDaSystemAdmin Team is analyzing the issue, Thanks for the details

**Comment by benfab** [comment]
@anupamaloke @jagadeeshnv We are facing the exact same issue, we will be happy to get the outcome of your analyze.

**Comment by jagadeeshnv** [comment]
@MikeDaSystemAdmin @benfab @apaqd We have committed the fix in devel, please verify

**Comment by jagadeeshnv** [comment]
Thank you for the quick repsonse
