### ISSUE TITLE
Dellemc modules not taken in account after Ansible upgrade to 2.10

### ISSUE THREAD

**Issue by ibt23sec5** [dell/dellemc-openmanage-ansible-modules#159]
After upgrade of `ansible`  to version 2.10 and reinstall of `dellemc` modules (with recommended method mentioned in README), these are no more available:

`ERROR! couldn't resolve module/action 'idrac_os_deployment'. This often indicates a misspelling, missing collection, or incorrect module path.`

And don't appears in the list of available modules:

`ansible-doc --list -t module` 

Versions:
```
python: 3.7.3
ansible: 2.10.0
dellemc: 2.1.2
omsdk: 445
```

**Comment by anupamaloke** [comment]
@ibt23sec5, with ansible 2.10, you will have to use ansible-collections. 
You can install [openmanage ](https://galaxy.ansible.com/dellemc/openmanage) collection from ansible galaxy:

```
ansible-galaxy collection install dellemc.openmanage
```

Once you have installed the collection, then you will have to modify your playbook to either use the FQCN (fully qualified collection name) for a module or you can use ```collections``` keyword. Please see [Ansible Documentation](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#using-collections-in-a-playbook)  on how to use collections within a playbook.

**Comment by ibt23sec5** [comment]
@anupamaloke I see, thanks !
