### ISSUE TITLE
export scp in JSON failed

### ISSUE THREAD

**Issue by praveenemc** [dell/dellemc-openmanage-ansible-modules#16]
Hello Team,
I'm testing the module dellemc_export_server_config_profile.yml and works fine with XML export for NFS shared directory. But export task as JSON is failing as below
"msg": {
        "Message": "Unable to export scp, exception occurred",
        "Status": "Failed",
        "file": "/home/praveen/NFSSHARE/X.X.X.X_20181114_050601_scp.json"
    }

I used devel branch for both Dell-EMC-Ansible-Modules-for-iDRAC and omsdk(sh build.sh 1.2 345)
pip version is 8.1.2,  python 2.7.5,  Ansible 2.4.20
Servers used: PowerEdge R630 idrac version 2.41.40.40 (Build 07)

Could you please check and suggest on this ?
Regards

**Comment by rajshekarp87** [comment]
Hi Praveen,

Thanks for trying out Dell EMC OpenManage Ansible Modules. Can you please share below details.

- Dell EMC OpenManage Ansible Modules version
- Playbook

Regards,
Rajshekar P

**Comment by rajshekarp87** [comment]
Hi Praveen,

Export/Import of Server configuration profile module is not supported on Server with iDRAC firmware 2.41.40.40. Ideally it will not work for NFS share as well. Please update iDRAC firmware to 2.50.50.50 and above and try running the module. Let us know if you still hit with an issue.

Thanks & Regards,
Rajshekar P

**Comment by praveenemc** [comment]
Hi Rajshekar, 

Thanks for your response !!
 - Playbook : is dellemc_export_server_config_profile.yml
- Dell EMC OpenManage Ansible Modules version
I cloned the devel branch of the git repo for both (below listed) and working on the same.
Dell EMC OpenManage Ansible Modules and 
Dell EMC OpenManage Python SDK ((sh build.sh 1.2 345)

Is this the version you mentioned? if not Please suggest how to find the version.

Regards
Praveen

**Comment by rajshekarp87** [comment]
Hi Praveen,

Thanks for providing required details. Both Master and devel has latest version (1.1). So you are using the latest version. Version details are available in "propereties.json" file (<Module_cloned_location>/Dell-EMC-Ansible-Modules-for-iDRAC/).

Please upgrade iDRAC firmware to 2.50.50.50 or above and then run the module. And let us know if you still hit with the issue.

Thanks & Regards,
Rajshekar P

**Comment by praveenemc** [comment]
Hi Rajshekar,

Tested the playbook dellemc_export_server_config_profile.yml against the PowerEdge serverR630 with iDRAC version to 2.50.50.50 (build 33).

Given below is the playbook(dellemc_export_server_config_profile.yml) contents:
---
- hosts: hosts
  connection: local
  name: Export Server Configuration Profile to local folder
  gather_facts: False

  tasks:
  - name: Export Server Configuration Profile to local folder
    dellemc_export_server_config_profile:
       idrac_ip:        "{{ idrac_ip }}"
       idrac_user:      "{{ idrac_user }}"
       idrac_pwd:       "{{ idrac_pwd }}"
       idrac_port:      "443"
       share_name:      "/home/praveen/NFSSHARE"
       scp_components:  "ALL"
       job_wait:        "False"
    tags:
        - scp_components_bios

  - name: Export Server Configuration Profile
    dellemc_export_server_config_profile:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_pwd:  "{{ idrac_pwd }}"
       job_wait: "False"
       share_name: "/home/praveen/NFSSHARE"
       scp_components: "ALL"
       export_format: "JSON"
       export_use: "Default"
    tags:
        - scp_components_nic


Below is the output:
[praveen@ansible-controller examples]$ ansible-playbook dellemc_export_server_config_profile.yml

PLAY [Export Server Configuration Profile to local folder] *******************************************************************************************************

TASK [Export Server Configuration Profile to local folder] *******************************************************************************************************
ok: [X.X.X.X]

TASK [Export Server Configuration Profile] ***********************************************************************************************************************
fatal: [X.X.X.X]: FAILED! => {"changed": false, "msg": {"Message": "Unable to perform Export", "Status": "Failed", "file": "/home/praveen/NFSSHARE/X.X.X.X_20181117_020603_scp.json"}}
        to retry, use: --limit @/home/praveen/Dell-EMC-Ansible-Modules-for-iDRAC/examples/dellemc_export_server_config_profile.retry

PLAY RECAP *******************************************************************************************************************************************************
10.X.X.X             : ok=1    changed=0    unreachable=0    failed=1

[praveen@ansible-controller examples]$
I found X.X.X.X_20181117_020457_scp.xml in the directory /home/praveen/NFSSHARE

Could you please help me to check what i'm missing in here.??
Please suggest.


Thanks
Praveen

**Comment by danvzla** [comment]
Hi Praven

Can you please run playbook in verbose mode and provide output
 
ansible-playbook dellemc_export_server_config_profile.yml -vvv

Regards

**Comment by rajshekarp87** [comment]
Hi Praveen,

Latest available iDRAC firmware is 2.60.60.60. Please update iDRAC firmware to latest version and let us know if you are still hitting with the issue. Below is the link.

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=cx8n2

Thanks & Regards,
Rajshekar P

**Comment by rajeevarakkal** [comment]
closing this issue, no heard from submitter from long
