### ISSUE TITLE
ome_template_network_vlan and Identity Pools

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#169]
The module "ome_template_network_vlan" does not appear to have a parameter to set the Identity pool, but when the module is applied to a template, it resets the Identity Pool to not selected.  If a template is already deployed with identities, the vlan update fails because it tries to modify the IO Pool which is not allowed.

The module needs to either not attempt to modify the Identity Pool at all, or a parameter to specify which pool it should have needs to be added.

Unable to use this module to manage VLANs assigned to an existing template that has been deployed with an Identity Pool in the current state.

Tested against templates in OpenManage Enterprise - Modular 1.20.10

**Comment by MallocArray** [comment]
Error message:
FAILED! => {"changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to complete the request because  IO Pool update on template not allowed.  does not exist or is not applicable for the resource URI.", "MessageArgs": ["IO Pool update on template not allowed."], "MessageId": "CGEN1004", "RelatedProperties": [], "Resolution": "Check the request resource URI. Refer to the OpenManage Enterprise-Modular User's Guide for more information about resource URI and its properties.", "Severity": "Critical"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: Bad Request"}

**Comment by jagadeeshnv** [comment]
@MallocArray The Issue has been fixed. Kindly Verify this

**Comment by jagadeeshnv** [comment]
@MallocArray Please let us know by reopening if not fixed
