### ISSUE TITLE
dell firmware update issue

### ISSUE THREAD

**Issue by kumaresan078** [dell/dellemc-openmanage-ansible-modules#17]
Hi,

I am trying to update firmware via ansible using dell-emc-ansible-module but it fails with below error.Can someone help me out?

Playbook:

---
- hosts: all
  connection: local
  name: Update Firmware Inventory
  gather_facts: False

  tasks:
  - name: Update Firmware Inventory
    dellemc_install_firmware:
       idrac_ip:        " {{ inventory_hostname }}"
       idrac_user:      "test"
       idrac_pwd:       "password"
       share_name:      "192.168.17.18:/racadm/firmware/"
       share_user:
         required: False
       share_pwd:
         required: False
       share_mnt: "/mnt/"
       reboot:     False
       job_wait:   True

Output:

fatal: [192.168.17.47]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "idrac": null,
            "idrac_ip": " 192.168.17.47",
            "idrac_port": 443,
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_user": "test",
            "job_wait": true,
            "reboot": false,
            "share_mnt": "/mnt",
            "share_name": "192.168.17.18:/racadm/firmware/",
            "share_pwd": "{'required': False}",
            "share_user": "{'required': False}"
        }
    },
    "msg": "Error: 'NoneType' object has no attribute 'use_redfish'"
}

Contents of firmware directory:

[root@test]# ls -lrt
total 83
-rw-r--r-- 1 root root 60937340 Nov 17 13:23 ESM_Firmware_MXKG2_LN32_2.91_A00.BIN
-rw-r--r-- 1 root root 10852356 Nov 17 13:23 BIOS_0F4YY_LN_6.6.0.BIN
-rw-r--r-- 1 root root 13612935 Nov 17 13:23 Lifecycle-Controller_Legacy_Application_0WFGM_LN_1.7.5.4_A00.BIN
[root@test]

Also is there way to integrate this module with openmanage? We have openamnager installed which we use for firmware update.

Regards
Kumaresan

**Comment by anupamaloke** [comment]
@kumaresan078 , the firmware update modules expects a catalog file and a firmware repository on a network share (CIFS or NFS). You can use [Dell EMC Repository Manager](https://www.dell.com/support/article/us/en/04/SLN312652/en) to create a firmware repository for your servers and export the repository to a network share along with a catalog file. 

All these modules work out-of-band by directly invoking the iDRAC REST/WS-Man APIs and therefore no agent (OpenManage Server Administrator or OMSA in short) is required to be running on server.  

HTH

**Comment by rajeevarakkal** [comment]
Closing this issue now since there is no update for a long time. Try out our latest `idrac_firmware` module and let us know in case you still face any issues
