### ISSUE TITLE
ome_discover module needed

### ISSUE THREAD

**Issue by TrevorSquillario** [dell/dellemc-openmanage-ansible-modules#172]
To automate the setup of OME this is an important module to get on the roadmap if it's not already on there.

**Comment by grantcurell** [comment]
@TrevorSquillario I'd be willing to take this one!

**Comment by TrevorSquillario** [comment]
@grantcurell I ended up writing this one and sending it over to the team. So this module should be included in the next release. I need to figure out unit testing before I submit pull requests here. Closing this issue.
