### ISSUE TITLE
Device driver issue

### ISSUE THREAD

**Issue by kumaresan078** [dell/dellemc-openmanage-ansible-modules#18]
Hi,

I have trying to run getfirmwareinventory.yml on dell R710 servers it works with some servers and some servers not.

I know this module supports only power generation 12 & above dell R710 falls in power generation 11.

I found the server drac lower on not working server hence upgraded the drac firmware that matches working server but still same issue.

Playbook:

---
- hosts: all
  connection: local
  name: Get Installed Firmware Inventory
  gather_facts: False

  tasks:
  - name: Get Installed Firmware Inventory
    dellemc_get_firmware_inventory:
       idrac_ip:        "{{ inventory_hostname }}"
       idrac_user:      "test"
       idrac_pwd:       "password"
    

Error:

fatal: [192.168.17.47]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "idrac": null,
            "idrac_ip": "192.168.17.47",
            "idrac_port": 443,
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_user": "test"
        }
    },
    "msg": "Could not find device driver for iDRAC with IP Address: 192.168.17.47"
}

Server Model: Dell R710
Drac Version : 6

Working server drac firmware version: 1.50 (Build 24)    Bios: 2.1.9
Not Working drac firmware version : 1.80 (Build 17) Bios: 2.0.13

Not sure why it doesn't work even updating drac firmware version.

Regards
Kumaresan

**Comment by rajshekarp87** [comment]
Hi Kumaresan,

Modules might work with 11G servers. But we are not claiming official support. We recommend to use Modules only with 12G, 13G and 14G PowerEdge Servers.

Thanks & Regards,
Rajshekar P

**Comment by rajeevarakkal** [comment]
@kumaresan078 Closing this issue as @rajshekarp87 answered the query
