### ISSUE TITLE
check mode on ome_network_vlan_info skipping execution

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#180]
Using 2.1.4 of the collection and when a task uses the ome_network_vlan_info module, if Ansible is executed with --check then the entire task is skipped.  If ran in normal mode, then it executes as expected.  This is causing problems with a playbook that I'm wanting to use the check mode to see if modifying a smart fabric uplink would make any changes, but it relies on information from ome_network_vlan_info to know what networks to add to the uplink.  Since the task is being skipped, the playbook cannot run in check mode.

With earlier versions (2.1.2 maybe?) I believe this was working, but it is also possible I wasn't running with --check at that time.

If a playbook is ran with --check, the tasks should still execute and if they are collecting information, they should continue to collect and register to a variable.  If the module would make a change, then it should evaluate if it would have made a change but not actually perform any modification.

**Comment by MallocArray** [comment]
Temporary workaround is to add check_mode: no to the task so it always executes, even when ansible is running in check mode

`
    - name: Collect current VLAN information

      ome_network_vlan_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
      register: current_vlans
      check_mode: no
`

**Comment by jagadeeshnv** [comment]
@MallocArray For any of our info modules, this feature is not enabled. This is expected

**Comment by MallocArray** [comment]
ok, but why?  Especially for info modules, there is no risk of running them while in check mode, so why would they be configured to skip?

**Comment by jagadeeshnv** [comment]
@MallocArray Our team had a discussion on this. Will update you regarding it.

**Comment by jagadeeshnv** [comment]
@MallocArray now this module supports check mode. Thank You
