### ISSUE TITLE
Documentation 2.1.4 ome_smart_fabric_uplink choices incorrect

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#181]
In the PDF for version 2.1.4 on page 110 for the module ome_smart_fabric_uplink, there are options listed for the ufd_enable parameter.

The options in the PDF are shown as "Enabled, or disabled".  The actual module is case sensitive and requires either option be capitalized:
`FAILED! => {"changed": false, "msg": "value of ufd_enable must be one of: Enabled, Disabled, got: disabled"}`

Documentation should be updated to reflect this.

**Comment by MallocArray** [comment]
Adding to this, in the list of parameters for ome_smart_fabric_uplink, only new_name is listed, but there is no reference to just "name" as a parameter in the table, although it is used in the examples.  Both should be listed in the parameter list.

**Comment by jagadeeshnv** [comment]
@MallocArray Thank you, we will fix this on priority

**Comment by jagadeeshnv** [comment]
@MallocArray Can you check with the latest commit. It has been addressed.
