### ISSUE TITLE
ome_application_network_proxy is skipped in check mode

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#187]
When running an ansible playbook with --check enabled, the task ome_application_network_proxy is skipped entirely, instead of running and reporting if it would change something.

Typically with check mode, a task still executes and reports OK or Changed if the task would make changes, but does not actually make any changes. I use this to ensure that things are set as desired or to understand if they will be changing when I run the task for real.

Since this task is skipped entirely, I'm unable to determine ahead of time if anything would be changed. I could add 
check_mode: no
which would always run the task, even if check mode is specified, but it would also make the change, which is undesireable.

**Comment by jagadeeshnv** [comment]
@MallocArray This has been fixed with the latest release 3.1.0. please verify

**Comment by jagadeeshnv** [comment]
@MallocArray Hope this is fine, will be closing this.

**Comment by MallocArray** [comment]
Confirmed as fixed.  Thank you.
