### ISSUE TITLE
module dellemc.openmanage.idrac_network use share_name as mandatory

### ISSUE THREAD

**Issue by weili302** [dell/dellemc-openmanage-ansible-modules#194]
Hi, I'm new to use the openmanage modules and met this issue. When I wanted to use module dellemc.openmanage.idrac_network to update some idrac network settings like idrac name and dns domain etc, then I got error:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: share_name"}

But I don't use share at all. so why share_name is needed as mandatory in module dellemc.openmanage.idrac_network?

**Comment by jagadeeshnv** [comment]
@weili302 that is used to provide the local path

**Comment by MallocArray** [comment]
The parameter name "share_name" is incredibly misleading if it really just means a local path on the Ansible server, as anytime a share is mentioned, I immediately assume NFS or CIFS.

**Comment by grantcurell** [comment]
@weili302 

你会做这样就好了。用 {{ playbook_dir }} 替代 "share_name"
You can use the below instead. Replace share_name with {{ playbook_dir }}

{
  "ANSIBLE_MODULE_ARGS": {
      "idrac_ip": "<YOUR_IP>",
      "idrac_user": "root",
      "idrac_password": "password",
      "auto_detect": "Disabled",
      "share_name": "{{ playbook_dir }}",
      "share_user": "some_username",
      "share_password": "some_password"
  }
}
