### ISSUE TITLE
Use attributes in dellemc_configure_bios 

### ISSUE THREAD

**Issue by jjeganathan** [dell/dellemc-openmanage-ansible-modules#21]
Hello,

When using dellemc_configure_bios from your example, I have an error.

```
    - name: Configure boot 
      dellemc_configure_bios:
         idrac_ip:   "{{ idrac_ip }}"
         idrac_user: "xxxxxx"
         idrac_pwd: "xxxxxx"
         attributes:
           BootMode : "Bios"
           OneTimeBootMode: "Enabled"
           BootSeqRetry: "Enabled"
		   
TASK [Configure boot] ***********************************************************************************
[DEPRECATION WARNING]: boot_mode, nvme_mode, secure_boot_mode, onetime_boot_mode and boot_sequence 
options have been deprecated, and will be removed. Please use the attributes option for Bios attributes 
configuration instead.{"idrac_user": "xxxxxx", "share_name": null, "idrac_port": 443, "share_mnt": null, 
"boot_mode": null, "nvme_mode": null, "share_pwd": null, "onetime_boot_mode": null, "boot_sequence": 
null, "boot_sources": null, "attributes": {"BootMode": "Bios", "BootSeqRetry": "Enabled", 
"OneTimeBootMode": "Enabled"}, "idrac_pwd": "********", "secure_boot_mode": null, "idrac_ip": 
"xxxxxx", "share_user": null}. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [phy-16]: FAILED! => {"changed": false, "msg": {"Message": "Failed to set value for attribute OneTimeBootMode", "Status": "Failed"}}
```

No error found when using BootMode only.

Thanks !

**Comment by rajshekarp87** [comment]
Hi Jeganathan,

Thanks for trying out Dell EMC OpenManage Ansible Modules.

"Enabled" is not an applicable option for "OneTimeBootMode". You need to provide proper BIOS/UEFI boot source.
Example: OneTimeBootMode: "NIC.PxeDevice.1-1"

Thanks & Regards,
Rajshekar P

**Comment by jjeganathan** [comment]
Thanks for your reply. I just wanted to try your example from the documentation.
But your solution doesn't seem to work in my usecase.

I debugged and indeed "Enabled is not <enum 'OneTimeBootModeTypes'>"
But when I was looking into the code, it looks like it only accepts:
- Disabled
- OnetimeBootSeq
- OneTimeHddSeq
- OneTimeHddSeq
- OneTimeUefiBootSeq
- OneTimeCustomBootSeqStr
- OneTimeCustomHddSeqStr
- OneTImeCustomUefiBootSeqStr

**Comment by rajeevarakkal** [comment]
@jjeganathan Closing this issue as @rajshekarp87  answered your issue
