### ISSUE TITLE
Server discovery task

### ISSUE THREAD

**Issue by pineappleray66** [dell/dellemc-openmanage-ansible-modules#214]
Hello All

i am not able to find a server discovery task is there one avlible?

seems a fundimental task to be missing.

thank you

**Comment by jagadeeshnv** [comment]
@pineappleray66  This feature is not available as of now. Will update when we add it to the pipeline

**Comment by pineappleray66** [comment]
thank you

**Comment by liamwh** [comment]
Hi @jagadeeshnv,

I would like to upvote this request. I am unsure whether we can automatically deploy servers using Ansible at the moment? Can you please advise how we can automate the below manual process?

Our manual workflow to deploy a new server looks like so:

1. On iDRAC configure directory services (for AD login)
2. On OME trigger device discovery by:
Choosing "Device Type" as Server, Dell iDRAC
Check "enable trap reception from discovered iDRAC servers and MX7000 chassis"
Check "Set Community String for trap destination from Application Settings use NPA

**Comment by jagadeeshnv** [comment]
@pineappleray66  We have added the ome_discovery module. 
@liamwh 
On iDRAC configure directory services (for AD login)
_Will get back on this_
1. On OME trigger device discovery by:
2. Choosing "Device Type" as Server, Dell iDRAC
_The following features are available in the module_
Check "enable trap reception from discovered iDRAC servers and MX7000 chassis"
Check "Set Community String for trap destination from Application Settings use NPA

**Comment by jagadeeshnv** [comment]
@pineappleray66 @liamwh  will be closing this. Please provide your feedback if any, by reopening this
