### ISSUE TITLE
Onboarding Task

### ISSUE THREAD

**Issue by pineappleray66** [dell/dellemc-openmanage-ansible-modules#215]
All

is it possible to create a single onboarding task via ansible?

thanks

**Comment by pineappleray66** [comment]
HI
i have searched all the API areas but can still not locate anything to help with creating this task
can you help
thanks

**Comment by jagadeeshnv** [comment]
discovery module will be added in the coming month

**Comment by jagadeeshnv** [comment]
@pineappleray66 ome_discovery module has been added
