### ISSUE TITLE
 ansible-playbook dellemc_get_system_inventory.yml --Where is the result

### ISSUE THREAD

**Issue by liweibenz** [dell/dellemc-openmanage-ansible-modules#22]
ansible-playbook dellemc_get_system_inventory.yml --Where is the result

**Comment by felixs88** [comment]
@liweibenz, verbose mode is required to add in the command line options, that gets the more output from the successful shown.

`ansible-playbook dellemc_get_system_inventory.yml -vvv`

**Comment by liweibenz** [comment]
thanks

Felix Stephen <notifications@github.com> 于2018年12月5日周三 下午7:04写道：

**Comment by anupamaloke** [comment]
@liweibenz, you need to turn on the verbosity option (-vvv or higher) to see the returned data. Alternatively, you can use the [debug module](https://docs.ansible.com/ansible/latest/modules/debug_module.html) to print the return value:

```
anupam@ubuntu:~/workspace/virtualenvs/ansible-om-devel/Dell-EMC-Ansible-Modules-for-iDRAC$ cat getinventory.yml
---
- hosts: all
  connection: local
  name: Get PowerEdge server system inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: python

  tasks:
    - name: Get system inventory
      dellemc_get_system_inventory:
        idrac_ip:   "{{ idrac_ip }}"
        idrac_user: "root"
        idrac_pwd:  "calvin"
      register: result

    # Set system inventory to a fact variable
    - set_fact:
        idrac_facts: “{{result.ansible_facts[idrac_ip].SystemInventory}}”

    # Print the complete system inventory
    - debug:
        var: idrac_facts

    # Print only iDRAC attributes from the idrac_fact variable
    - debug:
        var: idrac_facts[“iDRAC”]
```

**Comment by rajeevarakkal** [comment]
I hope this issue is closed with appropriate verbose level while invoking the playbook. Closing the defect now
