### ISSUE TITLE
Where are AnsibleFailJson and AnsibleExitJson defined? Missing test dependencies?

### ISSUE THREAD

**Issue by grantcurell** [dell/dellemc-openmanage-ansible-modules#237]
I'm spinning myself up on unit testing with Ansible and am struggling with the import nomenclature. I've been able to adjust a lot of it for my own environment to get it to work. However, one piece I'm missing are the following in common.py:

```
from ansible_collections.dellemc.openmanage.tests.unit.plugins.modules.utils import set_module_args, AnsibleFailJson, \
    AnsibleExitJson
from ansible_collections.dellemc.openmanage.tests.unit.compat.mock import MagicMock
```

`MagicMock` I can just import separately with `unittest.mock import MagicMock`. It looks like in other collections it is bundled, but it's missing in the dellemc collection:

*Edit*: I figured this out - I see in the docs you are meant to copy this.

![image](https://user-images.githubusercontent.com/35169230/106625329-919b7d00-6544-11eb-8c5e-7cf54b76db50.png)
![image](https://user-images.githubusercontent.com/35169230/106625897-21412b80-6545-11eb-9edc-0d8d51ae8f6d.png)

I see [Ansible says it should be bundled](https://docs.ansible.com/ansible/latest/dev_guide/testing_units_modules.html#use-of-mocks)) with Ansible itself.

I also couldn't find any reference to `AnsibleFailJson` or `AnsibleExitJson` in the entire project.

![image](https://user-images.githubusercontent.com/35169230/106621227-5ac36800-6540-11eb-9795-6da0460e341d.png)

Reading through [Ansible's guide on debugging](https://docs.ansible.com/ansible/latest/dev_guide/testing_units_modules.html#a-complete-example) it looks like these are custom defined exceptions that should be somewhere in the project.

I can't tell if I'm missing something, particularly since I just taught myself all this, or if those definitions are missing from the project.

**Comment by jagadeeshnv** [comment]
@grantcurell Please refer https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/tests/README.md for the tests dependencies

**Comment by jagadeeshnv** [comment]
@grantcurell Hope this solved the issue

**Comment by grantcurell** [comment]
> @grantcurell Hope this solved the issue

Ah sorry man. I'll just close this out - I had already seen that but I've been working other coding projects so I haven't circled back around to try it out again. I'll close this though - I don't want it cluttering your board 😂
