### ISSUE TITLE
Does this collection support Dell EMC PowerSwitch Nxx00 Series ?

### ISSUE THREAD

**Issue by woyteck1** [dell/dellemc-openmanage-ansible-modules#238]
I am trying to find out if these modules support Dell EMC PowerSwitch N1100 Series switches...
These switches run DellEMC OpenManage. 

Thanks
W.

**Comment by jagadeeshnv** [comment]
@woyteck1 These modules support DellEMC iDRAC and DellEMC OpenManage Enterprise configuration only. Not switches
