### ISSUE TITLE
Could not find device driver for iDRAC with IP address: <ip address>

### ISSUE THREAD

**Issue by davehouser1** [dell/dellemc-openmanage-ansible-modules#241]
**Module:** dellemc.openmanage.idrac_lifecycle_controller_logs

**Problem:** I keep getting this error when trying to use the dellemc-openmanage-ansible-modules device driver

`Could not find device driver for iDRAC with IP address: <ip address>`

**Note:** This module worked fine a week ago. Recently we changed the IP addresses of our iDrac servers to a new network. What is odd is I am able to reach the servers with out problems. I can ssh to the idrac systems and ping back to my system running the playbooks on this new network.

What am I missing here? Don't think I need to upgrade the modules as they were just working.

**Comment by anaterth** [comment]
@davehouser1 
I have encountered this issue when I provided the wrong password.  The error really doesn't indicate that is the issue, but I would double-check the credentials used.

**Comment by davehouser1** [comment]
@anaterth that was it.
The playbook was using active directory credentials to login. I changed it to root and it worked. Looking closer our migration did some AD / DNS ip & host changes. Misconfiguration on our part. 
Yes that error is misleading. Maybe Dell can implement a conditional to check for login success first, then provide an error based on the results.
