### ISSUE TITLE
idrac_firmware module errors with "msg": "'PercentComplete'" but still applies firmware updates

### ISSUE THREAD

**Issue by matthewit2** [dell/dellemc-openmanage-ansible-modules#246]
I'm running the idrac_firmware module to update some new r640 servers and the task always fails with "msg": "'PercentComplete'". In the iDRAC I see the job goes through and applies firmware updates and even pauses for the required reboots. It's getting that job status back to Ansible that seems to be the issue.

TASK [config-dell_servers : Update firmware from repository on a Network Share] ****************************************
task path: /mnt/c/nrtc/roles/config-dell_servers/tasks/main.yml:9
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp `"&& mkdir "` echo $HOME/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908 `" && echo ansible-tmp-1615924091.4240675-3380-222251120664908="` echo $HOME/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/remote_management/dellemc/idrac_firmware.py
<localhost> PUT /root/.ansible/tmp/ansible-local-3365aanbejaz/tmpr7jqn0rn TO /root/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908/AnsiballZ_idrac_firmware.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908/ /root/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908/AnsiballZ_idrac_firmware.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908/AnsiballZ_idrac_firmware.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1615924091.4240675-3380-222251120664908/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_idrac_firmware_payload_kgzk7en3/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py", line 391, in main
  File "/tmp/ansible_idrac_firmware_payload_kgzk7en3/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py", line 334, in update_firmware
  File "/usr/local/lib/python3.6/site-packages/omdrivers/lifecycle/iDRAC/iDRACJobs.py", line 352, in get_job_status_redfish
    if (jobdetail_data['PercentComplete'] < 100) or (100 < jobdetail_data['PercentComplete']):
fatal: [esxi06]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "apply_update": true,
            "catalog_file_name": "r640 test_1.00_Catalog.xml",
            "idrac_ip": "10.1.0.76",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "admin",
            "ignore_cert_warning": true,
            "job_wait": true,
            "reboot": true,
            "share_mnt": "/mnt/c/project/binaries/executables/dell_r640",
            "share_name": "\\\\10.1.0.251\\dell_r640",
            "share_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "share_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "share_user": "acadmin"
        }
    },
    "msg": "'PercentComplete'"
}

**Comment by jagadeeshnv** [comment]
Hi @matthewit2 Can you confirm the version of `dellemc.openmanage` collections in use? `ansible-galaxy collection list dellemc.openmanage`

**Comment by matthewit2** [comment]
Hi Jagadeesh,

 

I have to apologize, this specific error was from the idrac_firmware module
included in the Ansible 2.9 baseline (v2.8), not the dellemc.openmanage
community collection.

 

I did pull down the community collection (v3.1.0) and have the same (but
more verbose) error. The idrac_firmware module is at version 2.1.0 (which
seems odd). I've attached that log here.

 

Matthew Meyer

Systems Architect

World Wide Technology

714.338.6725 (desk)

 

From: Jagadeesh N V ***@***.***> 
Sent: Tuesday, March 23, 2021 4:59 AM
To: dell/dellemc-openmanage-ansible-modules
***@***.***>
Cc: Meyer, Matthew ***@***.***>; Mention
***@***.***>
Subject: Re: [dell/dellemc-openmanage-ansible-modules] idrac_firmware module
errors with "msg": "'PercentComplete'" but still applies firmware updates
(#246)

 

Hi @matthewit2
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fmatthewit2&data=04%7C01%7CMatthew.Meyer2%40wwt.com%7C86b0adc893444248b1e
608d8edf310ca%7Ca2d8e6b4e26e44218f3dec288c827c7d%7C1%7C0%7C63752097551007220
2%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haW
wiLCJXVCI6Mn0%3D%7C1000&sdata=ktPbGa2Dqfny4naWVn7oAT90zmDVsXDEYKl0mayTWp4%3D
&reserved=0>  Can you confirm the version of dellemc.openmanage collections
in use? ansible-galaxy collection list dellemc.openmanage

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fdell%2Fdellemc-openmanage-ansible-modules%2Fissues%2F246%23issuecomment-
804843827&data=04%7C01%7CMatthew.Meyer2%40wwt.com%7C86b0adc893444248b1e608d8
edf310ca%7Ca2d8e6b4e26e44218f3dec288c827c7d%7C1%7C0%7C637520975510082196%7CU
nknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJ
XVCI6Mn0%3D%7C1000&sdata=c7%2FxoebdQbiles1TrjxUwpRfMUkfq%2F3DAPQdVTYnRJM%3D&
reserved=0> , or unsubscribe
<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAPJ7S72MKIAE6BZMGJ5KE6DTFB7AVANCNFSM4
ZJHKM5A&data=04%7C01%7CMatthew.Meyer2%40wwt.com%7C86b0adc893444248b1e608d8ed
f310ca%7Ca2d8e6b4e26e44218f3dec288c827c7d%7C1%7C0%7C637520975510082196%7CUnk
nown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXV
CI6Mn0%3D%7C1000&sdata=maLcJGDBpvdA2Ik2aCOcbq%2Fqi4WnBAn4xiZ6IVoGBAc%3D&rese
rved=0> .
<https://github.com/notifications/beacon/APJ7S725GELQO3LFLEGCMT3TFB7AVA5CNFS
M4ZJHKM5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF74PCMY
.gif> 


[root@WWTATC-JL5Q1JEH nrtc]# ansible-playbook deploy_1.yml --tags firmware -i baseline-inventory.ini

PLAY [Configure ESXi Servers] ******************************************************************************************

TASK [config-dell_servers : Update firmware from repository on a Network Share] ****************************************
fatal: [esxi01]: FAILED! => {"changed": false, "msg": "HTTP Error 400: Bad Request", "update_status": {"error": {"@Message.ExtendedInfo": [{"Message": "Firmware versions on server match catalog, applicable updates are not present in the repository.", "MessageArgs": [], ***@***.***": 0, "MessageId": "IDRAC.2.2.SUP029", "RelatedProperties": [], ***@***.***": 0, "Resolution": "No response action is required.", "Severity": "Warning"}], "code": "Base.1.7.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}}
...ignoring
changed: [esxi02]

PLAY RECAP *************************************************************************************************************
esxi01                     : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
esxi02                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@WWTATC-JL5Q1JEH nrtc]#
- name: Update firmware from repository on a Network Share
  dellemc.openmanage.idrac_firmware:
    idrac_ip:       "{{ idrac }}"
    idrac_user:     "{{ dell_idrac['account name'] }}"
    idrac_password: "{{ dell_idrac['password'] }}"
    share_name:     '\\{{ mgmtip }}\dell_r640'
    share_user: "acadmin"
    share_pwd: "{{our_password}}"
    share_mnt: "/mnt/c/nrtc/binaries/executables/dell_r640"
    catalog_file_name: "r640 test_1.00_Catalog.xml"
    reboot: true
    job_wait: true
  vars:
    idrac: "{{lookup('dig', '{{inventory_hostname}}-idrac.{{domain}}')}}"
    mgmtip: "{{lookup('dig', 'mgmt-laptop.'+'{{domain}}')}}"
  delegate_to: localhost
  ignore_errors: true
  tags: firmware
