### ISSUE TITLE
Get system inventory - Error

### ISSUE THREAD

**Issue by leandrocarpenter** [dell/dellemc-openmanage-ansible-modules#247]
Hello good afternoon
I'm starting the creation of playbooks for idracs, when I'm going to run the playbook to collect information from systems, I get the error below:
"PLAY [Get system inventory]
skipping: no hosts matched "

Attached, prints of the playbook and inventory could help me locate my error?
![inventory](https://user-images.githubusercontent.com/76078156/111833622-32fe4880-88d1-11eb-97c2-fa92a8fb4243.JPG)
![Playbook](https://user-images.githubusercontent.com/76078156/111833628-3396df00-88d1-11eb-9364-8af73355652f.JPG)

**Comment by leandrocarpenter** [comment]
![image](https://user-images.githubusercontent.com/76078156/111833734-57f2bb80-88d1-11eb-8e7d-a6d62d814e43.png)

**Comment by jagadeeshnv** [comment]
@leandrocarpenter Please check your inventory file, and update the "hosts" field in the playbook appropriately

**Comment by anupamaloke** [comment]
Closing this issue.
