### ISSUE TITLE
unexpected reboot when setting PxeDev1VlanId

### ISSUE THREAD

**Issue by mories76** [dell/dellemc-openmanage-ansible-modules#25]
I have two issues,
The value of PxeDev1VlanId apparently needs to be quoted, otherwise I get the error message Failed to set values. The example form the manual show an unquoted example. 
The above was just a little inconveniece.

When I set the PxeDev1VlanId with the quoted value, the caused a reboot which I didn't expect.

**Comment by anupamaloke** [comment]
@mories76, could you please share the playbook that you are running?

**Comment by rajeevarakkal** [comment]
@mories76 Since there is no update, we are closing this issue for now
