### ISSUE TITLE
idrac_firmware module errors when no updates are applicable to the system

### ISSUE THREAD

**Issue by matthewit2** [dell/dellemc-openmanage-ansible-modules#250]
I'm having an issue where the idrac_firmware module errors on any host that is fully up to date against our firmware repo. In the example below, two dell 640's were updated. ESXI01 was fully patched and received the error. ESXI02 had an applicable idrac upgrade and was successful.

idrac_firmware module version: "2.1.0"
dellemc.openmanage collection version: "3.1.0"

[root@WWTATC]# ansible-playbook deploy_1.yml --tags firmware -i baseline-inventory.ini

PLAY [Configure ESXi Servers] ******************************************************************************************

TASK [config-dell_servers : Update firmware from repository on a Network Share] ****************************************
fatal: [esxi01]: FAILED! => {"changed": false, "msg": "HTTP Error 400: Bad Request", "update_status": {"error": {"@Message.ExtendedInfo": [{"Message": "Firmware versions on server match catalog, applicable updates are not present in the repository.", "MessageArgs": [], "MessageArgs@odata.count": 0, "MessageId": "IDRAC.2.2.SUP029", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "No response action is required.", "Severity": "Warning"}], "code": "Base.1.7.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}}
changed: [esxi02]

PLAY RECAP *************************************************************************************************************
esxi01                     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
esxi02                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@WWTATC]#

**Comment by anupamaloke** [comment]
@matthewit2, this issue has been fixed. Could you please try with the latest version of the ```dellemc.openmanage``` collection? Please reopen this issue if you are still running into this same issue.
