### ISSUE TITLE
ome_template not idempotent

### ISSUE THREAD

**Issue by TrevorSquillario** [dell/dellemc-openmanage-ansible-modules#255]
When running the module if the template exists it fails breaking the task sequence that follows. This does not follow the Ansible guidelines for module development. Need to check to see if a template by this name exists and if it does return changed = false. This would apply to the 'create' and 'import' actions. 

```fatal: [MX7000-C38ZZZZ]: FAILED! => {"changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to create the template because the template name  001Test  already exists.", "MessageArgs": ["001Test"], "MessageId": "CTEM1027", "RelatedProperties": [], "Resolution": "Enter a unique template name and retry the operation.", "Severity": "Warning"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: Bad Request"}```

**Comment by ImranJMughal** [comment]
@anupamaloke - Hi Anupam - Do you know when this will be looked at? 

Thanks

Imran

**Comment by anupamaloke** [comment]
@ImranJMughal, it is in the list of our To-Do items. We will be prioritizing it for next couple of minor releases.

**Comment by MallocArray** [comment]
+1 to this as it also applies to the modify command, always showing it changed something, even if the template had the modifications already in place

**Comment by sachin-apa** [comment]
Merged as part of the PR #[391](https://github.com/dell/dellemc-openmanage-ansible-modules/pull/391) Release 5.2.0
