### ISSUE TITLE
Documentation clarification - why is a share required?

### ISSUE THREAD

**Issue by grantcurell** [dell/dellemc-openmanage-ansible-modules#257]
Hello - fellow Dell guy here. I've had a couple of customers ask me this question and while I can go read the source code and provide an answer they aren't sure how to figure it out. I had one ask me recently, "Why for enabling or disabling syslog is a share required?" Ex:

https://www.dell.com/support/manuals/en-lv/openmanage-ansible-modules/omam_ug_3/configure-syslog?guid=guid-4dc3797b-3981-4dec-ba30-d845e0c63c46&lang=en-us

When I first received this question I was able to reverse engineer the code and realize we were calling into an SDK and from there was able to find [this explanation](https://github.com/dell/omsdk/blob/devel/docs/idrac.rst#prerequisites).

Is there somewhere in the Ansible docs the reason for the share is explained? Or did I maybe misunderstand what it's being used for?

**Comment by anupamaloke** [comment]
@grantcurell, the syslog module uses a server configuration profile to update the iDRAC syslog attributes on iDRAC 7/8 and iDRAC 9. During the initial stages when the module was being developed, iDRAC7/8 only supported importing a SCP file from a remote network share (CIFS or NFS). Therefore ```share_name``` argument was added to specify the network share location that iDRAC will use to import the SCP. Now that iDRAC7/8 also supports local file streaming within the HTTPS message playload itself (firmare version 2.50.50.50 and above), I agree that ```share_name``` should not be a required parameter anymore. It should be made as an optional argument instead or removed altogether. Be default, the module should use the temp directory for the creating the temporary SCP file that it will later dump into the SCP import buffer in the import SCP operation's HTTPS payload. 

I usually provide the ```"{{ playbook_dir }}"``` as the ```share_name``` argument in my playbooks. I will close this issue and create a new enhacement request to make ```share_name``` as an optional argument. Let me know if that sounds good to you.

**Comment by grantcurell** [comment]
Ah that makes sense! Sounds good!

**Comment by grantcurell** [comment]
@anupamaloke was asked about this today - just for tracking purpose do you happen to have the number for the enhancement request? I have an interested customer that would like to keep track of it

**Comment by anupamaloke** [comment]
@grantcurell, I have this enhancement request added to our internal backlog. As of now, we still need to get this prioritized. I will keep you updated with the progress.

**Comment by Klaas-** [comment]
I am not sure I am fully understanding this. Do you need to put in the share name a valid path? Or why do you use `"{{ playbook_dir }}"` ? From your answer it reads more like the share_name is not used at all during normal operations?

Does this also apply to all other uses of share_name? For example in `dellemc_configure_idrac_eventing` it doesn't seem needed either if I just want to configure a smtp server, right?

**Comment by Klaas-** [comment]
I played around, it seems the module needs a writeable directory to the user executing the task. the directory is used to store temporary files

**Comment by grantcurell** [comment]
> @grantcurell, I have this enhancement request added to our internal backlog. As of now, we still need to get this prioritized. I will keep you updated with the progress.

Hey @anupamaloke! I'm still getting questions about this from pretty much every customer who is new to our Ansible modules and they routinely confuse it with other things.

For example: Right now I am working with a customer who wants to enable syslog but can't figure out where to set the remote server (I haven't either actually - looks like you have to push it via SCP separate from the Ansible module?). Unfortunately, they were confused by the share and spent a whole bunch of time messing with the share only to discover it was unnecessary. Does there happen to be an ETA on when the enhancement might be implemented?
