### ISSUE TITLE
dellemc_configure_idrac_users error

### ISSUE THREAD

**Issue by matt13rox** [dell/dellemc-openmanage-ansible-modules#26]
Hi guys
When I use dellemc_configure_idrac_users module to update the password of a user, the module fails with the following error:
--------------------------------------------
autonomous-controller-automation ➤ ansible-playbook -i inventories/r640 r640-idrac-password-change.yml -vvv                                                                          git:master*
ansible-playbook 2.7.5
  config file = /home/mjoseph/my-dev/autonomous-controller-automation/ansible.cfg
  configured module search path = [u'/home/mjoseph/my-dev/autonomous-controller-automation/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Using /home/mjoseph/my-dev/autonomous-controller-automation/ansible.cfg as config file
/home/mjoseph/my-dev/autonomous-controller-automation/inventories/r640/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/home/mjoseph/my-dev/autonomous-controller-automation/inventories/r640/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/mjoseph/my-dev/autonomous-controller-automation/inventories/r640/hosts inventory source with ini plugin

PLAYBOOK: r640-idrac-password-change.yml ********************************************************************************************************************************************************
1 plays in r640-idrac-password-change.yml

PLAY [Change iDRAC default password] ************************************************************************************************************************************************************
META: ran handlers

TASK [r640-server/idrac-password-change : Update iDRAC user password] ***************************************************************************************************************************
task path: /home/mjoseph/my-dev/autonomous-controller-automation/roles/r640-server/idrac-password-change/tasks/main.yaml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mjoseph
<127.0.0.1> EXEC /bin/sh -c 'echo ~mjoseph && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999 `" && echo ansible-tmp-1546950649.02-88032968222999="` echo /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999 `" ) && sleep 0'
Using module file /home/mjoseph/my-dev/autonomous-controller-automation/library/dellemc_configure_idrac_users.py
<127.0.0.1> PUT /home/mjoseph/.ansible/tmp/ansible-local-10148Syl2UU/tmpm9N380 TO /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999/AnsiballZ_dellemc_configure_idrac_users.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999/ /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999/AnsiballZ_dellemc_configure_idrac_users.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999/AnsiballZ_dellemc_configure_idrac_users.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/mjoseph/.ansible/tmp/ansible-tmp-1546950649.02-88032968222999/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "modify",
            "authenticationprotocol_users": null,
            "enable_users": null,
            "idrac_ip": "10.234.79.8",
            "idrac_port": 443,
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_user": "root",
            "ipmilanprivilege_users": null,
            "ipmiserialprivilege_users": null,
            "privacyprotocol_users": null,
            "privilege_users": null,
            "protocolenable_users": null,
            "share_mnt": null,
            "share_name": "/tmp",
            "share_pwd": null,
            "share_user": null,
            "solenable_users": null,
            "user_name": "root",
            "user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": {
        "Data": {
            "Message": "Failed to get job detail",
            "Status": "Failed"
        },
        "Status": "Failed",
        "StatusCode": 401,
        "retval": false
    }
}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
------------
Thank you!

**Comment by anupamaloke** [comment]
@matt13rox , could you please share the following details:

- iDRAC FW version
- Do you get the error every time when you run the playbook ?
- Do you see a new SCP Import JOB created on the iDRAC even when the playbook fails?

**Comment by dfitz82** [comment]
I have the same problem.  
How do I look up the iDRAC FW version?

It only happens when a user updates themselves, idrac_user == user_name.

**Comment by anupamaloke** [comment]
@dfitz82, at this point in time, you can not use the openmanage modules to update the same user password. However, this functionality has now been provided in the [redfish_command](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_command.py) module:

```
  - name: Update user password
    redfish_command:
      category: Accounts
      command: UpdateUserPassword
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      id: "{{ id }}"
      new_password: "{{ new_password }}"
```

**Comment by mihai-satmarean** [comment]
Hi there,
dell is finally making some good stuff,
even if same functionality is provided by redfish would be useful to find out the answer to this question too @matt13rox can you paste the playbook contents too? 
Thanks!

**Comment by matt13rox** [comment]
Sorry I missed the notifications.
I was trying to update the password of the same user and ended up using redfish_command module.

**Comment by rajeevarakkal** [comment]
@matt13rox Are you still facing this issue?

**Comment by matt13rox** [comment]
I ended up using redfish_command module and it works fine with it. You can close this issue

**Comment by rajeevarakkal** [comment]
@matt13rox  We currently doesn't support  password modification same user used for connecting to iDRAC.

**Comment by jagadeeshnv** [comment]
@matt13rox We have addressed this issue with the new module "idrac_user" Kindly verify and let us know

**Comment by jagadeeshnv** [comment]
@matt13rox Can you please verify and close this issue?

**Comment by jagadeeshnv** [comment]
@matt13rox This has been fixed module 'idrac_user' as stated above. Hence closing this issue. Thank You
