### ISSUE TITLE
add documentation for new modules

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#261]
Hello. its great that you developed new modules configuration compliance.  Would be possible to add modules info into this page including some samples ?

https://docs.ansible.com/ansible/latest/collections/dellemc/openmanage/index.html#dellemc-openmanage

cheers

**Comment by anupamaloke** [comment]
@markatdxb the documentation has now been updated on the Ansible documentation site.
