### ISSUE TITLE
ome_template_network_vlan against OME-M does not Propagate VLAN settings

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#267]
When using the ome_template_network_vlan module to add VLANs to a Template against an OME-M system in MX7000 chassis running firmware 1.20.10, the VLANs are not propagated, even if the Template has the checkbox set to "Propagate VLAN settings immediately"

The VLANs do show up in the template when viewing it in the GUI, but the propagation is not triggered when modified using the Ansible module.  This leads to lots of confusion when a template has the VLANs but they are not working on the sleds because they were not propagated.

Ideally the Ansible module would respect whatever setting is currently set on the existing template, but a workaround would be to have a parameter in the module to propagate the VLANs or not.

**Comment by jagadeeshnv** [comment]
@MallocArray With the latest release propagate_vlan is a option with default true.

**Comment by MallocArray** [comment]
Confirmed that this is working as expected without needing to add extra parameters.
