### ISSUE TITLE
ome_firmware doesn't support check mode

### ISSUE THREAD

**Issue by dwettstein** [dell/dellemc-openmanage-ansible-modules#274]
Currently the module `ome_firmware` doesn't support Ansible's check mode. 

While the module `ome_firmware_baseline_compliance_info` can be used to query if e.g. a device is compliant or not, and if not why respectively which components are not compliant, supporting the check mode in `ome_firmware` would allow to see what would be done/changed before actually doing anything.

**Comment by anupamaloke** [comment]
Corollary of #252

**Comment by anupamaloke** [comment]
Closing this and tracking this as part of #252

**Comment by dwettstein** [comment]
Hello @anupamaloke. It might be that this issue relates #252, but in my opinion it is not the same.
For sure idempotence needs to be fixed, but fixing it doesn't mean that [Ansible's check mode](https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html) is then available as well. This needs to be implemented additionally.

**Comment by anupamaloke** [comment]
@dwettstein, I agree.
