### ISSUE TITLE
ome_firmware_catalog_with_job_tracking.yml example behaves unexpectedly

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#281]
In the current version of ome_firmware_catalog_with_job_tracking.yml example playbook, the line:
```yaml
      failed_when: "'catalog_status' not in result"
```
causes unexpected results if used in an actual playbook.

On the first run with the provided fields, the task returns a value of "ok" even when it is adding the new catalog as a brand new item.
On a second run, it will return a failure, stating:
 FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "failed_when_result": true, "msg": "No changes found to be applied."}

Both of these issues are caused by the failed_when incorrectly returning values.

On the first execution, since the provided values do not point to a valid catalog, the job actually fails because it cannot connect to the repository since it is just a placeholder, but the failed_when parameter marks it as "ok" since 'catalog_status" does appear in the result, but 'Status" is Failed in result.

On the second execution, the same failed_when triggers a failure because 'catalog_status" does not appear in the result variable, but the msg field has a value of "No changes found to be applied"

2 proposed fixes:

- Remove the "failed_when" line entirely, as the module should take care of recognizing any failures internally and report accurately
- Update the example playbooks, both ome_firmware_catalog_with_job_tracking.yml and ome_firmware_catalog.yml, to have a valid source of a Dell repository, which is used in the module file ome_firmware_catalog.py
```yaml
source: "downloads.dell.com"
```

**Comment by jagadeeshnv** [comment]
@MallocArray We have job tracking as part of the module now. We will update this example accordingly. 
https://github.com/dell/dellemc-openmanage-ansible-modules/blob/32abc4cea3cb102fab051408f327403bc9ae0683/plugins/modules/ome_firmware_catalog.py#L101

**Comment by jagadeeshnv** [comment]
Job wait is enabled by default, probably we will discuss internally and can provide an explicit example on how to skip job tracking. That example will be taken care.

**Comment by jagadeeshnv** [comment]
This example has been removed. This change will be part of ansible-galaxy collections by 6/28 this month.
