### ISSUE TITLE
redfish_idrac_firmware iDRAC8: Target firmware version doesn't support HTTP protocol

### ISSUE THREAD

**Issue by janr7** [dell/dellemc-openmanage-ansible-modules#286]
Hi Dell

Using this module to update Firmware on a server, R730, with 2.60.60.60 to 2.70.70.70 give me this error with either the .exe or .d7 firmware file.
This all works fine with updating iDRAC9
The tick in the iDRAC setup for Redfish is on.

Using: dellemc-openmanage-2.1.1

        "module_args": {
            "baseuri": "ltapp201k",
            "image_uri": "/global/instserv/packages/firmware/iDRAC_2.70.70.70_A00.exe",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "transfer_protocol": "HTTP",
            "username": "Administrator"
        }
    },
    "msg": "**Target firmware version doesn't support HTTP protocol.**"

Help appreciated.
Thanks so much,
Jan

**Comment by anupamaloke** [comment]
@janr7, I am guessing that the HttpPushUri support for Redfish Simple Update might not be available for iDRAC 2.60.60.60. Could you see please run the following cURL GET command (or from a Postman) on the ```/redfish/v1/UpdateService``` resource and check whether you see "HTTP" or "HTTPS" in the supported ```TransferProtocol@RedfishAllowableValues``` and the ```HttpPushUri``` attribute in the response (marked with ```<=========```)?

```
$ curl -k -s 'https://root:calvin@192.168.1.1/redfish/v1/UpdateService' | python -m json.tool
{
    "@odata.context": "/redfish/v1/$metadata#UpdateService.UpdateService",
    "@odata.id": "/redfish/v1/UpdateService",
    "@odata.type": "#UpdateService.v1_2_0.UpdateService",
    "Actions": {
        "#UpdateService.SimpleUpdate": {
            "TransferProtocol@Redfish.AllowableValues": [ <=====================
                "HTTP"
            ],
            "target": "/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate"
        },
        "Oem": {
            "DellUpdateService.v1_0_0#DellUpdateService.Install": {
                "InstallUpon@Redfish.AllowableValues": [
                    "Now",
                    "NowAndReboot",
                    "NextReboot"
                ],
                "target": "/redfish/v1/UpdateService/Actions/Oem/DellUpdateService.Install"
            }
        }
    },
    "Description": "Represents the properties for the Update Service",
    "FirmwareInventory": {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory"
    },
    "HttpPushUri": "/redfish/v1/UpdateService/FirmwareInventory", <=================================
    "Id": "UpdateService",
    "Name": "Update Service",
    "ServiceEnabled": true,
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    }
}

```

**Comment by janr7** [comment]
Hi anupamaloke

On investigation we found that the message was merely a warning and that the update actually did happen. 
Thank you for the attention you gave to this issue.

Below our output

curl -k -s 'https://Admin:C4****@ltapp201k/redfish/v1/UpdateService'| python -m json.tool
{
    "@odata.context": "/redfish/v1/$metadata#UpdateService.UpdateService",
    "@odata.id": "/redfish/v1/UpdateService",
    "@odata.type": "#UpdateService.v1_2_0.UpdateService",
    "Actions": {
        "#UpdateService.SimpleUpdate": {
            "TransferProtocol@Redfish.AllowableValues": [
                "HTTP"
            ],
            "target": "/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate"
        },
        "Oem": {
            "DellUpdateService.v1_0_0#DellUpdateService.Install": {
                "InstallUpon@Redfish.AllowableValues": [
                    "Now",
                    "NowAndReboot",
                    "NextReboot"
                ],
                "target": "/redfish/v1/UpdateService/Actions/Oem/DellUpdateService.Install"
            }
        }
    },
    "Description": "Represents the properties for the Update Service",
    "FirmwareInventory": {
        "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory"
    },
    "HttpPushUri": "/redfish/v1/UpdateService/FirmwareInventory",
    "Id": "UpdateService",
    "Name": "Update Service",
    "ServiceEnabled": true,
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    }
}

Regards.

**Comment by anupamaloke** [comment]
@janr7, thanks for the update. I guess I was not clear in my response earlier. The ```redfish_firmware_update``` module supports the Pull or Push method to update the firmware.

- Pull method: Also called as ```SimpleUpdate```. You can provide a URL to the firmware binary hosted on a remote HTTP share. The ```redfish_firmware_update``` module checks  whether the path provided in the ```image_uri``` argument starts with ```http```. If yes, then it tries to use this method. I guess this is the method that you are using in your playbook.
- Push method: This is usually for the cases where the firmware binary is located on a local path. If ```HttpPushUri``` is supported as part of the iDRAC Redfish Update Service, then the module uses HTTP multipart request to transfer the firmware binary image to iDRAC and update the firmware.

> On investigation we found that the message was merely a warning and that the update actually did happen.

Could you please provide a little bit information on this please? From the output that you had posted above, it looks that the task failed with the error message ```Target firmware version doesn't support HTTP protocol.```.  Are you saying that the module worked as intended and the simple firmware update was success?
