### ISSUE TITLE
Forced reboot in dellemc_configure_bios module

### ISSUE THREAD

**Issue by tsquillario** [dell/dellemc-openmanage-ansible-modules#29]
On line 321 of library/dellemc_configure_bios.py you are setting reboot=True. We should probably be making this a parameter. I checked the beta branch and didn't see the dellemc_configure_bios module. What is the plan for this module? Did it move to something else? 

Did a quick search and this module needs updated as well library/dellemc_idrac_lc_attributes.py

I can submit a pull request for these if you'd like? Submit to beta branch?

https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/blob/master/library/dellemc_configure_bios.py#L321

**Comment by tsquillario** [comment]
After some testing I think I found a bug. Even when manually setting idrac.config_mgr.apply_changes(reboot=False) the server automatically reboots. Is this how it's supposed to operate? I'm setting AcPwrRcvry: "On"

R640
iDRAC Firmware Version | 3.21.23.22
omsdk (1.2.345)
Latest master branch 1.1

**Comment by tsquillario** [comment]
It appears the much better way to accomplish this is to switch to the redfish_config module. Seems redfish is the future of ansible and iDRAC.

**Comment by anupamaloke** [comment]
@tsquillario, whilst configuration of some BIOS attribute does not require server reboot, some do. I am assuming setting the "AcPwrRcvry" option does require a reboot for BIOS job to run. We will confirm and get back.

One advantage that dellemc_configure_bios module has over the redfish_config module is you can use just one task to set the entire BIOS attributes.

**Comment by rajeevarakkal** [comment]
@tsquillario Are you still facing the issue?

**Comment by tsquillario** [comment]
Yes. Just tested with the latest modules. There is no `reboot` option. It just reboots the server without the user knowing it will. How is a customer supposed to know that changing `AcPwrRcvry` requires a reboot and they should stage it? I run into this quite a bit with customers with other attributes, it's a mystery.

**Comment by anupamaloke** [comment]
@tsquillario, all BIOS configuration changes require a reboot for them to be applied. ```dellemc_configure_bios``` module automatically takes care of the reboot. 

Other option would be to use the ```redfish_config``` module to set the BIOS attributes, schedule a BIOS configuration job using ```idrac_redfish_command``` modules followed by graceful restart using ```redfish_command```. You can refer to a sample playbook here: https://github.com/dell/redfish-ansible-module/blob/master/playbooks/bios/set_bootmode_uefi.yml

**Comment by rajeevarakkal** [comment]
@tsquillario;  `dellemc_configure_bios` is leverages iDRAC's `System Configuration Profile` feature capabilities (import) to apply desired BIOS configuration changes. `System Configuration Profile` doesn't support staging the parameter concept rather it offers you a end-to-end configuration apply in one go, however you can schedule the playbook execution in an appropriate maintenance window.

Like @anupamaloke  mentioned, if you wish to stage parmeter settings, you can leverage other set of modules time being

I hope this clarifies this question

**Comment by tsquillario** [comment]
I haven't really had any complaints from customers on this issue so I'll close it for now.
