### ISSUE TITLE
ome_firware - service tag and baseline name interop

### ISSUE THREAD

**Issue by ImranJMughal** [dell/dellemc-openmanage-ansible-modules#294]
Hi

Is there a way to remediate firmware and use both a system tag and a baseline name?

In device clusters we want the ability to remediate a single device only even if others in the group also are not at the baseline level.

Thanks

Imran

**Comment by ImranJMughal** [comment]
not sure if this is the same as #239

**Comment by jagadeeshnv** [comment]
@ImranJMughal This is in the pipeline, will update whenever this is planned

**Comment by ImranJMughal** [comment]
Thanks - We really could do with this, as we group hosts in clusters and cant remediate a cluster group as OME is not aware of cluster services on the host. Therefore a new host may end up remediating the whole cluster group and bringing services down. We could have workaround to add to temp groups etc but that is messy.
