### ISSUE TITLE
ome_diagnostics to support debug logs

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#308]
##### Description
ome_diagnostics supports starting a SupportAssist Collection from a MX blade, but does not currently have a "log_selectors" entry to enable "Debug Logs" when collecting.
Support has told me in the past to always collect Debug Logs when doing a collection, as it doesn't add much time and prevents them from coming back to ask for it later.

##### New or existing component
ome_diagnostics

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
Closed by #402
