### ISSUE TITLE
Unexpected return value when iSM is running on host

### ISSUE THREAD

**Issue by qwertzlbert** [dell/dellemc-openmanage-ansible-modules#31]
System: VxRail E560
iDRAC Firmware: 
OS: esxi 6.7 

Ansible will return with the error message when using 'dellemc_change_power_state': "Error: unhashable type: 'list'" if the iSM Module is running on the host OS (see picture attached)

"Workaround": Shutdown the system before using 'dellemc_change_power_state' so iSM is not running anymore.

[ansible_requirements.txt](https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/files/2811699/ansible_requirements.txt)
![ism-bug](https://user-images.githubusercontent.com/19959427/51970282-cfa5c800-2476-11e9-9303-0d10336f32c2.JPG)

**Comment by rajeevarakkal** [comment]
@qwertzlbert  Are you still facing this issue?

**Comment by qwertzlbert** [comment]
Sorry I tried to get hands on another vxrail to test, but I failed. As this is  an old issue I would close this for now and see it as fixed (Codewise quite a lot happend between my issue request and now).
