### ISSUE TITLE
ome_diagnostics option to extract log from lead chassis only

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#310]
##### Description

In ome_diagnostics, if log_type is set to 'application', then logs are extracted from all chassis in an MX7000 group.  This is fine as a default, but many times Support only requests logs from the Lead chassis.  By having all chassis logs saved, the end user must find which of the multiple files are from the Lead.

Suggestions to have an optional parameter to request only the Lead or all chassis so the end user can control the behavior.
Suggestion: 
  lead_only: yes
or
  lead_chassis_only: yes

##### New or existing component
ome_diagnostics

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MallocArray** [comment]
Anything I can do to request a priority bump on this one?

**Comment by anupamaloke** [comment]
@MallocArray, we will be picking this up for 5.2.0 release
