### ISSUE TITLE
4.0 modules missing in Ansible documentation

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#311]
##### Question

Hi , do you have any plans to update https://docs.ansible.com/ansible/latest/collections/dellemc/openmanage/index.html#plugins-in-dellemc-openmanage with info about all new modules ?

**Comment by anupamaloke** [comment]
@markatdxb, the Ansible documentation get automatically updated with every minor or major Ansible community release. The latest documentation for dellemc.openmanage collection version 4.0.0 will be picked up as part of the Ansible community release 4.6.0 around last week of September. Ansible community release follows a 3 week release cadence, whereas dellemc.openmanage collection follows a 4 week / monthly release cadence.
