### ISSUE TITLE
dellemc_idrac_storage_volume does not work

### ISSUE THREAD

**Issue by jimr6007** [dell/dellemc-openmanage-ansible-modules#33]
I get this error whenever I try to create a volume:
"msg": "returned status code doesn't match with the expected success code"

What does work is using the Ansible raw module to run racadm commands directly
https://docs.ansible.com/ansible/latest/modules/raw_module.html

So that tells me that it's not likely an issue with my server etc.

If I create a volume manually and use the "view" module it works.

Even tried that, copied the results, deleted the manually created volume and then used the info I got from the "view" mode to try again but it still fails.

My guess is it's failing to select either the controller or the disk/disks correctly.

full error message:

fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "capacity": null, 
            "controller_id": "RAID.Integrated.1-1", 
            "disk_cache_policy": "Default", 
            "idrac_ip": "10.16.85.4", 
            "idrac_port": 443, 
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "idrac_user": "root", 
            "media_type": null, 
            "number_dedicated_hot_spare": 0, 
            "protocol": null, 
            "raid_init_operation": null, 
            "raid_reset_config": "False", 
            "read_cache_policy": "NoReadAhead", 
            "span_depth": 1, 
            "span_length": 1, 
            "state": "create", 
            "stripe_size": 65536, 
            "volume_id": null, 
            "volume_type": "RAID 0", 
            "volumes": [
                {
                    "drives": {
                        "id": [
                            "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1"
                        ]
                    }, 
                    "name": "test-vol"
                }
            ], 
            "write_cache_policy": "WriteThrough"
        }
    }, 
    "msg": "returned status code doesn't match with the expected success code"
}

**Comment by jimr6007** [comment]
this is on a 730xd, iDrac 8, Enterprise

**Comment by jimr6007** [comment]
I'm not much of a developer but with a little hacking I was able to make the SDK tell me a little more and what I now see is:

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to export scp, exception occurred"}

I thought an export of something was not happening in the case of RAID config operation.

Help please......

**Comment by jimr6007** [comment]
yes, I'm using omsdk-1.2.345 and the dellemc_idrac_storage_volume module

**Comment by jimr6007** [comment]
bios version 2.8.0
LC 2.61.60.60

**Comment by jimr6007** [comment]
WARN: Changing isFolder to false, as it is not directory
response.status_code:503, success_code:[202]
No handlers could be found for logger "omdrivers.lifecycle.iDRAC.iDRACConfig"

**Comment by jimr6007** [comment]
Got it to wok in Python 3 because with that I saw more logging info.

So the fix is obvious but it sure would have been nice to see that error message when running with Python 2.X

503, "error": {"error": {"@Message.ExtendedInfo": [
{"Message": "A job operation is already running. Retry the operation after the existing job is completed.", "MessageArgs": [], "MessageArgs@odata.count": 0, "MessageId": "IDRAC.1.6.RAC067 9", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "Wait until the running job is completed or delete the scheduled job and retry the operation.", "Severity": "Warning"}

**Comment by rajeevarakkal** [comment]
@jimr6007 The latest issue you have encountered is because iDRAC is busy with a running job. Hope that is closed and the module is working fine.

**Comment by rajeevarakkal** [comment]
@jimr6007 Since there is no response for sometimes; closing this defect now. Let usknow if ou are facing any issues

**Comment by mapdeep** [comment]
i am getting the same error
"module_stdout": "WARN: Changing isFolder to false, as it is not directory\nmsg_id=SYS043\nSeverity=Informational\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
