### ISSUE TITLE
Boot order - new module

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#332]
##### Description

Would be great if you could develop module which would be able to change boot order on the servers

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
A new module `idrac_boot` has been added into the 6.1.0 release. Closed by #438
