### ISSUE TITLE
quick deploy networking config

### ISSUE THREAD

**Issue by Eladpriel** [dell/dellemc-openmanage-ansible-modules#336]
##### Description
Would be great if you could develop module which allowing quick deploy configuration like IP address, vlan and etc

##### New or existing component
I would like to have the capability to configure quick deploy on the MX, to set the IP address of the sled before it is being deployed.

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@Eladpriel, quick deploy configuration is now available as part of #355
