### ISSUE TITLE
The error was: AttributeError: iDRAC

### ISSUE THREAD

**Issue by singhs11** [dell/dellemc-openmanage-ansible-modules#337]
##### Question

I am attempting to use "dellemc.openmanage.idrac_os_deployment" to mount an ISO for ESXi build, but getting the below error.  I tried the following version of Ansible collections:

dellemc-openmanage-2.1.5
dellemc-openmanage-4.2.0

I received the same error with both.  What am I missing?  Or is this a bug? 

##### Details

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: iDRAC
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1635975497.7953186-18429-157697117493497/AnsiballZ_idrac_os_deployment.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1635975497.7953186-18429-157697117493497/AnsiballZ_idrac_os_deployment.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1635975497.7953186-18429-157697117493497/AnsiballZ_idrac_os_deployment.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_dellemc.openmanage.idrac_os_deployment_payload_r0acv4qk/ansible_dellemc.openmanage.idrac_os_deployment_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_os_deployment.py\", line 168, in <module>\n  File \"/tmp/ansible_dellemc.openmanage.idrac_os_deployment_payload_r0acv4qk/ansible_dellemc.openmanage.idrac_os_deployment_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_os_deployment.py\", line 160, in main\n  File \"/tmp/ansible_dellemc.openmanage.idrac_os_deployment_payload_r0acv4qk/ansible_dellemc.openmanage.idrac_os_deployment_payload.zip/ansible_collections/dellemc/openmanage/plugins/module_utils/dellemc_idrac.py\", line 46, in __enter__\n  File \"/usr/local/lib/python3.7/enum.py\", line 354, in __getattr__\n    raise AttributeError(name) from None\nAttributeError: iDRAC\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by anupamaloke** [comment]
@singhs11, could you please try it out in a new python3 virtualenv and report whether you are still facing this issue?

**Comment by anupamaloke** [comment]
@singhs11, I will be closing this issue. Please reopen the issue or create a new one in case you are still running into same error.

**Comment by singhs11** [comment]
Thanks @anupamaloke.  A new virtualenv with python3 resolved the issue.
