### ISSUE TITLE
Why can't I use /etc/ansible/hosts instead of individual IP addresses in playbooks?

### ISSUE THREAD

**Issue by zogness** [dell/dellemc-openmanage-ansible-modules#34]
Why can't I use hostnames in /etc/ansible/hosts? I have dozens of iDRACs and they all have proper hostnames. How do I use them instead of IP addresses?

**Comment by anupamaloke** [comment]
@zogness, you can use hostnames in the /etc/ansible/hosts. You just need to set the "idrac_ip" to the "{{ ansible_host }}" in your playbook. Let us know if you face any issue.

**Comment by rajeevarakkal** [comment]
@zogness Closing this issue Hope your Query has been clarified
