### ISSUE TITLE
Manage EventFilters

### ISSUE THREAD

**Issue by Klaas-** [dell/dellemc-openmanage-ansible-modules#342]
##### Description
I would like to use ansible to manage the EventFilters

##### New or existing component
I think it's a new component, it is exported in SCPs.

`"FQDD": "EventFilters.*"`

Direct use case for me, I want to configure memory mail warnings. so `MEM_1_2#Alert#Email` I want to set to enabled.

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xSpeedy** [comment]
Any updates on this issue?
With IPMILan.1.AlertEnable it is possible to activate the alerts for all selected Eventfilters. But is it not possible to manage the event filters. 
As a workaround it is possible to manage the eventfilters with the racadm command:

`racadm eventfilters <eventfilters command type> `
(https://www.dell.com/support/manuals/de-de/poweredge-r440/idrac9_6.xx_racadm_pub/eventfilters?guid=guid-f6f39929-07f5-4d8b-a163-bd9658cd323c&lang=en-us)

**Comment by Klaas-** [comment]
@xSpeedy I think you may need to poke your dell representative about this if you're a big customer :) I am not seeing this happening anytime soon, I created PRs for it like 2 years ago :)
