### ISSUE TITLE
Firmware.yml is not working.

### ISSUE THREAD

**Issue by cheppsr** [dell/dellemc-openmanage-ansible-modules#350]
##### Component Name
ome_firmware.yml not working

##### Ansible Version

```paste below
ansible [core 2.11.3]
```

##### Playbook used

```paste below

```

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@cheppsr, could you please post the playbook and the error that you are receiving?

**Comment by anupamaloke** [comment]
@cheppsr, closing this issue as there have been no updates since long. Please feel free to reopen this issue if you run into any issue with ```ome_firmware``` module.
