### ISSUE TITLE
How install collection release 5.0.1

### ISSUE THREAD

**Issue by ranguitamartin** [dell/dellemc-openmanage-ansible-modules#363]
##### Question
What method should I follow install release 5.0.1?

##### Details

I have installed module using ansible-galaxy, but this method instaled master branch with version 3.5.0, if i specify collection same release installed and if I try install manually with  install.py  in branch collection , this is not posible because some files and folder not is found, merged is required?

What step should  I  follow?

**Comment by sachin-apa** [comment]
@ranguitamartin it is a standard steps that is mentioned as part of the [Readme](ansible-galaxy collection install dellemc.openmanage) should install 5.0.1 patch release packages.

**Comment by ranguitamartin** [comment]
I follow this steps installing download tarball and installing with ansible-galay collection install too, in both cases release installed was 3.5.0, because when i launch playbook
y have error with SSL. I put validation_certs: False, following instruction and this parameter is ignore.
I see dellemc_idrac.py installed and this py is version 3.5.0, no is indicated in commit 14064b24e4,  this commit added funcionality validation_certs in release 5.0.1

for this reason i ask how can install release 5.0.1

**Comment by sachin-apa** [comment]
Just tried installing in my machine it seems to install correctly 
Galaxy Instaltiom`ansible-galaxy collection install dellemc.openmanage -f
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/dellemc-openmanage-5.0.1.tar.gz to /root/.ansible/tmp/ansible-local-1726443vpo4ljix/tmp4jvi_4qw/dellemc-openmanage-5.0.1-he9_gpf1
Installing 'dellemc.openmanage:5.0.1' to '/root/.ansible/collections/ansible_collections/dellemc/openmanage'
dellemc.openmanage:5.0.1 was installed successfully
`

**Comment by ranguitamartin** [comment]
> Just tried installing in my machine it seems to install correctly Galaxy Installation
> 
> ```
> ansible-galaxy collection install dellemc.openmanage -f
> Starting galaxy collection install process
> Process install dependency map
> Starting collection install process
> Downloading https://galaxy.ansible.com/download/dellemc-openmanage-5.0.1.tar.gz to /root/.ansible/tmp/ansible-local-1726443vpo4ljix/tmp4jvi_4qw/dellemc-openmanage-5.0.1-he9_gpf1
> Installing 'dellemc.openmanage:5.0.1' to '/root/.ansible/collections/ansible_collections/dellemc/openmanage'
> dellemc.openmanage:5.0.1 was installed successfully
> ```
> 
> @ranguitamartin Can you please force install and paste an output here may be you have multiple version installed. if so please remove the older version of collection using command ` rm -rf <old_coll_path>/dellemc/openmanage`

hi have installed again and show version 5.0.1 but validate_cert is ignored in playbook

**Comment by ranguitamartin** [comment]
So installation version is resolved, fail with validation issue is other issue

**Comment by sachin-apa** [comment]
> hi have installed again and show version 5.0.1 but validate_cert is ignored in playbook

@ranguitamartin parameter is `validate_certs` can you please confirm if you have used the same not `validate_cert` ?

**Comment by ranguitamartin** [comment]
yes, sorry i use validate_certs: False in playbook, but is ignored

**Comment by sachin-apa** [comment]
@ranguitamartin  Sorry I'm not clear on whether issue is resolved or not .. if issue resolved please let us know if can close or please reply with the sample playbook, module that you are trying to execute.

**Comment by ranguitamartin** [comment]
I open this issue asking installation 5.0.1, this is resolved, but i cannot use this module because validation_certs is ignored and  this collection check SSL certification in url.

**Comment by sachin-apa** [comment]
> I open this issue asking installation 5.0.1, this is resolved, but i cannot use this module because validation_certs is ignored and this collection check SSL certification in url.

@ranguitamartin Can you please post the playbook you are trying to run ?
Also , please post output of the command `env` from the linux CLI.

**Comment by sachin-apa** [comment]
@ranguitamartin I'm closing the issue, please reopen if you are still facing the issue with the details
