### ISSUE TITLE
update doc on how to use with ansible

### ISSUE THREAD

**Issue by netmonk** [dell/dellemc-openmanage-ansible-modules#393]
##### Description
first time using those modules today to export log from idrac with ansible. 
Documentation is not really clear about how to really use it. 
First of all the module doesnt connect directly to idrac using ssh like we all (sysadmin) are used to. 
So basically ansible is not using idrac_ip as a direct connexion. 
In fact it need a linux (or any machine capable to run python ) to run the module which is going to connect to idrac after. 

So for exemple in a playbook, the task should be "delegate_to: localhost"  (the machine running the playbook) if this machine can access idrac with network.

**Comment by MallocArray** [comment]
You can also add 
```
connection: local
```
at the top of your playbook so you don't have to add the delegate_to on each task, although this gets complicated with Ansible Execution Environments and python modules, so I also add the delegate_to on each task as a general rule.

On all of my Dell related playbooks, I just have the `connection: local` at the top.

But you are right, this isn't in the examples, and it would help for it to be.
