### ISSUE TITLE
Module to manage Alert Policies in OME/M

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#404]
##### Description

There does not appear to be a module to manage Alert Policies in OME or OME-M.  I ran into this when using the module to configure Syslog Forwarder destination but without the associated policy, nothing was being sent

##### New or existing component

ome_alert_policies

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bobykus31** [comment]
Any progress on this? Without such a feature the SysLog.* attributes management is kind of pointless as the logs are not sent to any syslog server anyway even if it is configured. The correspondent iDrac cli command is

racadm eventfilters set -c idrac.alert.all -a none -n remotesyslog
