### ISSUE TITLE
Does idrac_os_deployment support HTTP boot?  

### ISSUE THREAD

**Issue by lianzxu** [dell/dellemc-openmanage-ansible-modules#413]
I can do http boot from iDRAC by setting remote file share in this format: http://<ip address>/name.iso. But it doesn't seem to work with dellemc.openmanage modules. Can you please confirm? 

I installed the Ansible module with the following command a few weeks ago:

ansible-galaxy collection install dellemc.openmanage

Thanks.

**Comment by sachin-apa** [comment]
@lianzxu : Thanks for submitting a question. 
**idrac_os_deployment** module doesn't support HTTP boot yet and it is part of our todo items. 
it is currently being tracked under issue [# 153](https://github.com/dell/dellemc-openmanage-ansible-modules/issues/153) 
Closing this issue, please reopen if necessary.
@anupamaloke
