### ISSUE TITLE
idrac_os_deployment failed to boot the host

### ISSUE THREAD

**Issue by lianzxu** [dell/dellemc-openmanage-ansible-modules#414]
Here is my task:

- name: Boot to ISO 
  dellemc.openmanage.idrac_os_deployment:
    idrac_ip: "{{hostvars[sno_node].sno_idrac_ip}}"
    idrac_user: "{{hostvars[sno_node].sno_idrac_user}}"
    idrac_password: "{{hostvars[sno_node].sno_idrac_pw}}"
    share_name: "{{ansible_default_ipv4.address}}:{{nfs_dir}}"
    iso_image: "{{rhcos_live_iso}}"
    expose_duration: 120
    validate_certs: False
  delegate_to: localhost

Here are the logs:

  msg: {
    Key: <null_index>,
    DeleteOnCompletion: false,
    InstanceID: DCIM_OSDConcreteJob:1,
    JobName: BootToNetworkISO,
    JobStatus: Failed,
    Message: General failure,
    MessageID: OSD2,
    Name: BootToNetworkISO,
    Status: Failed,
    retval: false,
    file: 10.x.y.z:/path/to/rhcos-4.9.0-x86_64-live.x86_64.iso
  }

- 10.x.y.z:/path/to/rhcos-4.9.0-x86_64-live.x86_64.iso works fine if booting with "Remote File Share" in iDRAC.

- Connectivity from Ansible controller to iDRAC works fine because I tested it with other task using "idrac_system_info". 

Are there any other helpful logs I can check for the failures?

Another question about "expose_duration". If I set "expose_duration=120", does it imply that I can't boot the host AGAIN with "idrac_os_deployment" until 2-hour timer expires?

Thank you.

**Comment by anupamaloke** [comment]
@lianzxu, `expose_duration` argument controls the amount of time the ISO is attached to the iDRAC licecycle controller. After expiry of `expose_duration`, idrac will automatically disconnect the ISO. 

As to why the idrac_os_deployment module is failing, it could be that an ISO image is already attached. You will have to detach the ISO image before attempting another run. At present, `idrac_os_deployment` module does not support detaching an already attached ISO image. This is among one of many TODO things for this module. So, in the meanwhile, we have also provided an ansible role that you can use to detach the image. This role supports both booting from an ISO image as well as detaching an ISO image. Following is the link: 
https://github.com/dell/redfish-ansible-module/tree/master/roles/idrac_os_deployment

**Comment by lianzxu** [comment]
Thank you very much for the information. It is very helpful.
