### ISSUE TITLE
[BUG]: dellemc.openmanage.ome_discovery timeout

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#417]
### Bug Description

Issue started with OME upgrade to the latest version 3.9.0 build 55
when running discovery module to delete discovery job the process times out randomly
is there any way to increase the read timeout of the module ?

### Component or Module Name

dellemc.openmanage.ome_discovery

### Ansible Version

Ansible 2.10.10

### Python Version

Python 3.6.8

### iDRAC/OME/OME-M version

OME 3.9 build 55

### Operating System

N/A

### Playbook Used

- name: Delete a discovery job
  dellemc.openmanage.ome_discovery:
    hostname: "ome"
    username: "username"
    password: "password"
    state: "absent"
    discovery_job_name: "servername"

### Logs

{
    "msg": "The read operation timed out",
    "invocation": {
        "module_args": {
            "hostname": "ome",
            "username": "username",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "absent",
            "discovery_job_name": "servername",
            "validate_certs": false,
            "schedule": "RunNow",
            "job_wait": true,
            "job_wait_timeout": 10800,
            "trap_destination": false,
            "community_string": false,
            "ignore_partial_failure": false,
            "port": 443,
            "timeout": 30,
            "discovery_id": null,
            "new_name": null,
            "discovery_config_targets": null,
            "cron": null,
            "email_recipient": null,
            "ca_path": null
        }
    },
    "_ansible_no_log": false,
    "attempts": 1,
    "changed": false,
    "retries": 11
}

### Steps to Reproduce

- name: Delete a discovery job
  dellemc.openmanage.ome_discovery:
    hostname: "ome"
    username: "username"
    password: "password"
    state: "absent"
    discovery_job_name: "servername"

### Expected Behavior

delete discovery job
the same playbook worked OK before the latest OME upgrade

### Actual Behavior

job times out

**Comment by sachin-apa** [comment]
@markatdxb Thanks for submitting the issue.

1. API timeout is defaulted to 30 sec, you can increase the value by sending the parameter **timeout** in the playbook.
2. Job wait logic has the job wait timeout defaulted to 10800 in the playbook, this means that the module will wait for the specified amount of time to check for the completion, if job is talking more time for completion then the parameter **job_wait_timeout** can be passed with a higher value in the playbook.

Please try this options and let us know the results.

**Comment by markatdxb** [comment]
Great thanks for hint.
