### ISSUE TITLE
idrac.use_redfish = True in dellemc_idrac_firmware.py question

### ISSUE THREAD

**Issue by ja07657** [dell/dellemc-openmanage-ansible-modules#42]
I am having issues with 14G servers running dellemc_idrac_firmware.yml from a network repo Catalog.xml - hope anyone can give me some ideas, please.

If trying to update firmware on 14G server, I get failed message: "Export of scp failed for firmware update".  it will work on 13G.
If I change the value of idrac.use_redfish in the the dellemc_idrac_firmware.py script from True to False, then 14G will work fine.

What is being utilized when idrac.use_redfish is False ?
What could be stopping this from working when it is set to True ?

**Comment by ja07657** [comment]
I see WS-MAN is used when = False

**Comment by anupamaloke** [comment]
@ja07657, that's right. When ```use_redfish``` is set to ```True```, then the modules use the Server Config Profile (SCP) to update the firmware.  Only caveat is that you need to locally mount the CIFS/NFS share where the firmware repository (update packages and catalog file) in read-write mode on the ansible controller host. The module then creates a SCP on the fly and writes it to the mounted path where the catalog and update packages are present, and then submits an import scp job to iDRAC.

**Comment by anupamaloke** [comment]
@ja07657, if you are okay with the above explanation, then shall I close this issue now?

**Comment by MarlonRodriguez** [comment]
I'm not the user that created this issue but it seems to me that you are missing the part on why it works on 13G but not 14G.  Also, how does WS-MAN makes it successful?  I dont expect you to explain all of that but how about a link to the documentation that has the information?  BTW your explanation makes a lot of sense, just hoping for completeness.

**Comment by rajeevarakkal** [comment]
@ja07657 We have a uniform approach for 13G and 14G in the latest `idrac_firmware` and also we have deprecated the `dellemc_idrac_firmware`; Let us know in case you facing any issues with this latest module. Closing this defect as of now
