### ISSUE TITLE
idrac_os_deployment: Unable to boot to service partition because the target service partition was not found in the boot list

### ISSUE THREAD

**Issue by lianzxu** [dell/dellemc-openmanage-ansible-modules#422]
I used module idrac_os_deployment to bootstrap two DELL poweredge R630 servers. The first one worked just fine. But I got error when bootstapping the second server: "Unable to boot to service partition because the target service partition was not found in the boot list.". 

I compared iDRAC firmware and other setting but didn't find anything obviously different. And the boot sequence is the same on both servers. I wonder what I have missed. Thank you.

![image](https://user-images.githubusercontent.com/98832962/175365868-c5082d60-c4e0-45f6-97b6-0ba705ce6458.png)

Here is the boot sequence:

![image](https://user-images.githubusercontent.com/98832962/175367142-5a416677-f163-4c75-a868-fd38410794bd.png)

**Comment by anupamaloke** [comment]
@lianzxu, Ansible modules will only make a REST API call to iDRAC to boot from a network ISO image. Do you see this error even when manually deploying the ISO image using iDRAC GUI?

**Comment by lianzxu** [comment]
We had to reset iDRAC twice. The issue is gone now. Thank you.
