### ISSUE TITLE
[FEATURE]: Remove Device from an openmanage static group

### ISSUE THREAD

**Issue by Wal-E9871** [dell/dellemc-openmanage-ansible-modules#424]
I am trying to remove a device from a static group and add it to another one however the parameter state : absent is not supported.

ome_device_group:
        hostname: '{{ ome_ip }}'
        username: '{{ ome_user }}'
        password: '{{ ome_pass }}'
        validate_certs: no
        name: '{{ static_group }}'
        state: "absent" # not yet supported
        device_service_tags:
          - '{{ Service_tag }}'

**Describe alternatives you've considered**

 The alternative is to remove the device from openmanage ,rediscover and add it to the desired group however this ome device remove module is not available.

Is there any update \ new module in the pipeline that could help reaching this task?

**Comment by anupamaloke** [comment]
@Wal-E9871 , removal of devices from OME static group is not supported in ansible module because there is no REST API support in OME. Also, I am not sure you can remove a device from a custom static group using WebUI in OME as well. One workaround you can use in meantime is to create a new static group with the right set of devices and delete the old  static group.

**Comment by Wal-E9871** [comment]
@anupamaloke : Removing a device from a group can be done from GUI by editing the static group and then deselect the device from the list.
if I am not wrong there is a REST API to remove a device from a static group using below:
https://www.dell.com/support/manuals/en-uk/dell-openmanage-enterprise-tech-release/lex_techrel_pub/groups-service?guid=guid-894c21ef-14f8-44ea-9e98-9e4e613ca4a3
The issue is that i have interactions between static groups , devices should move from a group to another depending on some conditions

**Comment by anupamaloke** [comment]
@Wal-E9871, I stand corrected. Thank you for sharing the REST API documentation. I have added this requirement to the backlog.

**Comment by anupamaloke** [comment]
@Wal-E9871, also let me know if this is something that you would like to submit a PR for :-)

**Comment by anupamaloke** [comment]
Closed by #438
