### ISSUE TITLE
Question: How to set Boot Sequence with idrac_bios module?

### ISSUE THREAD

**Issue by lianzxu** [dell/dellemc-openmanage-ansible-modules#427]
I can't find any example to set boot_sequence other than some notes in the use's guide (Dell EMC OpenManage Ansible Modules Version 5.0.0). 

Ensure that I(boot_mode) option is
provided to determine which boot
sequence is applied.
NOTE: This option is deprecated,
and will be removed in later version.
Use I(attributes) for configuring the
BIOS attributes.
NOTE: I(boot_sequence) is mutually
exclusive with I(boot_sources).

I extracted the FQDD using module dellemc.openmanage.idrac_system_info. I think the following 2 may be used for setting boot sequence:

                    "FQDD": "Disk.Virtual.0:RAID.Integrated.1-1",
                    "FQDD": "Disk.Virtual.1:RAID.Integrated.1-1",

I manually set boot sequence as below with PXE as the first one:

![image](https://user-images.githubusercontent.com/98832962/178062782-2a4cb37f-13df-41cb-a136-b53ebefde41c.png)

Then I set boot sequence with disk as the first one. Here is what I have in my playbook:

      attributes:
        boot_mode: "Uefi"
        boot_sequence:
          - Name : "Disk.Virtual.0:RAID.Integrated.1-1"
          - Name : "Disk.Virtual.1:RAID.Integrated.1-1"

There is no errors when running the book, but in boot manager I didn't see any changes in terms of boot sequence .

**Comment by anupamaloke** [comment]
@lianzxu, a new `idrac_boot` has been added in the latest 6.1.0 release. Please use this module for configuring the boot sources. Let me know if you run into any issue. I will keep this issue open for some time till we get your feedback.

**Comment by anupamaloke** [comment]
@lianzxu, I am closing this issue for now. Please open a new issue if you are still facing this error.
