### ISSUE TITLE
[QUESTION]: SMTP Still Requires IP Address 

### ISSUE THREAD

**Issue by dk-rbrown** [dell/dellemc-openmanage-ansible-modules#431]
After 6.0 release the idrac alerting and eventing was supposed to accept FQDN as a parameter to allow for the setup of alerting from an SMTP server. This would allow Amazon SES and other in house smtp servers whose ip changes quite frequently to be setup. 
However the playbook is still failing because it require an IP. 
Was this missed?

**Comment by anupamaloke** [comment]
@dk-rbrown, could you please confirm whether you are using the new `idrac_attributes` module for configuring the SMTP server?

```
- name: configure SMTP attributes
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ inventory_hostname }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: False
    idrac_attributes:
      EmailAlert.1.Enable: Enabled
      EmailAlert.1.Address: "test@smtpserver1.com"
      EmailAlert.1.CustomMsg: "Custom message 1"
      EmailAlert.2.Enable: Enabled
      EmailAlert.2.Address: "test@smtpserver2.com"
      EmailAlert.2.CustomMsg: "Custom message 2"
      EmailAlert.3.Enable: Enabled
      EmailAlert.3.Address: "test@smtpserver3.com"
      EmailAlert.3.CustomMsg: "Custom message 3"
      EmailAlert.4.Enable: Enabled      
      EmailAlert.4.Address: "test@smtpserver4.com"
      EmailAlert.4.CustomMsg: "Custom message 4"

**Comment by dk-rbrown** [comment]
Thank you for pointing me in this direction. I did not see this new module. After updating my EE and using these new modules I can set the parameters. Thank you again.
