### ISSUE TITLE
[QUESTION]: Are there any option to use one session ID for authentication

### ISSUE THREAD

**Issue by SeiketsuJael** [dell/dellemc-openmanage-ansible-modules#441]
### How can the team help?
I would like to know if there are any  options to use a config file that has the authentication/sessionID instead of initiating an session on every ansible task for OME?
**Details: ?**
Currently we are foreseeing an issue when it comes to hitting the maximum API sessions if we have multiple tasks that will use the ansible modules for OME. We can probably increase the threshold but I want to put it out there if there are any possible solutions of using a single authentication code for one playbook  execution.

Thank you in advance and would appreciate any answers.

**Comment by anupamaloke** [comment]
@SeiketsuJael, at present this is not supported by the modules. However, I agree that it could become an issue in future when you have multiple tools requesting user sessions from OME. One way to do it would be to have a new module to create user sessions and then modify existing set of modules to have an additional argument to accept x-auth tokens.

**Comment by SeiketsuJael** [comment]
@anupamaloke Thank you for the response, we will look forward to this feature. For the meantime we will increase the session threshold just to avoid future issues since we have multiple tools.
