### ISSUE TITLE
[FEATURE]: Inventory plugin from OME

### ISSUE THREAD

**Issue by tperrindell** [dell/dellemc-openmanage-ansible-modules#447]
**Describe the solution you'd like**
Create an inventory in AAP2 or AWX using OME data

**Describe alternatives you've considered**
This plugin from an external dev : https://gitlab.com/keiran.steele/dell-openmanage-ansible-inventory

**Additional context**
I think it is relevant when creating playbooks to manage an OME installation and/or iDRAC not to maintain an inventory manually when OME is a perfect inventory source.

**Comment by anupamaloke** [comment]
OME inventory plugin has been added in the v7.1.0 release as part of #465. 
At present, the inventory plugin only supports custom device groups (static and query). In v7.2.0, additional support is going to be added for the out-of-box device groups.

**Comment by sachin-apa** [comment]
OME inventory plugin has been updated to support all the groups in the v7.2.0 release as part of #468 .

Please do let us know if any issues. Closing this Feature as completed.
