### ISSUE TITLE
[BUG]: https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/EXECUTION_ENVIRONMENT.md#use-ansible-runner-to-verify-the-execution-environment 

### ISSUE THREAD

**Issue by ffirg** [dell/dellemc-openmanage-ansible-modules#461]
### Bug Description

According to https://github.com/dell/dellemc-openmanage-ansible-modules#prerequisites you now need python 3.9 do the docs needs to be updated as it currently states 3.8 under 2. Create a host file with the following entries:

### Component or Module Name

n/a

### Ansible Version

n/a

### Python Version

n/a

### iDRAC/OME/OME-M version

n/a

### Operating System

n/a

### Playbook Used

n/a

### Logs

n/a

### Steps to Reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

**Comment by sachin-apa** [comment]
Closing the issues as this is fixed with the Release 7.1.0 [PR](https://github.com/dell/dellemc-openmanage-ansible-modules/pull/465)
