### ISSUE TITLE
[QUESTION]:Support for DRAC8 redfish URI?

### ISSUE THREAD

**Issue by ayoustic** [dell/dellemc-openmanage-ansible-modules#463]
I'm having some trouble accessing redfish storage on R730xd PERC controllers via Redfish commands. Can you please advise whether I'm addressing this correctly?

Let's use code from the example playbooks:

`
- name: Enable controller encryption
    dellemc.openmanage.idrac_redfish_storage_controller:
      baseuri: "{{ drac_hostip }}"
      username: "{{ priv_user }}"
      password: "{{ priv_password }}"
      command: "EnableControllerEncryption"
      controller_id: "RAID.Integrated.1-1"
      mode: "LKM"
      key: "secretkey"
      key_id: "secretkeyid"
      validate_certs: false
    tags:
      - enable-encrypt
`
When the playbook runs, I get the following error message:

`fatal: [hostname redacted]: FAILED! => {"changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to complete the operation because the resource /redfish/v1/Dell/Systems/System.Embedded.1/Storage/DellController/RAID.Integrated.1-1 entered is not found.", "MessageArgs": ["/redfish/v1/Dell/Systems/System.Embedded.1/Storage/DellController/RAID.Integrated.1-1"], "MessageArgs@odata.count": 1, "MessageId": "IDRAC.1.6.SYS403", "RelatedProperties": [], "RelatedProperties@odata.count": 0, "Resolution": "Enter the correct resource and retry the operation. For information about valid resource, see the Redfish Users Guide available on the support site.", "Severity": "Critical"}, {"Message": "The resource at the URI /redfish/v1/Dell/Systems/System.Embedded.1/Storage/DellController/RAID.Integrated.1-1 was not found.", "MessageArgs": ["/redfish/v1/Dell/Systems/System.Embedded.1/Storage/DellController/RAID.Integrated.1-1"], "MessageArgs@odata.count": 1, "MessageId": "Base.1.2.ResourceMissingAtURI", "RelatedProperties": [""], "RelatedProperties@odata.count": 1, "Resolution": "Place a valid resource at the URI or correct the URI and resubmit the request.", "Severity": "Critical"}], "code": "Base.1.2.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}, "msg": "controller_id with id 'RAID.Integrated.1-1' not found in system"}
`
This would suggest that this implementation only supports the later versions of the DRAC. Is this the case? The documentation on the front page indicates that the modules support DRAC8 at firmware 2.83.83.83 and up. 

The machine in question is a Dell R730xd with a DRAC at firmware 2.83.83.83

The machine I'm launching ansible from has the following software versions for reference:

Ansible: 2.14.1
Python:  3.19.3
RHEL 8.7
dellemc collection: v7.0.0
omsdk 3.11

**Comment by anupamaloke** [comment]
@ayoustic, this is currently supported with iDRAC 9 only since the iDRAC8 does not have Redfish OEM API support for these features. Only way to do so with iDRAC 8 would be to use the legacy WS-Man APIs or racadm commands with Ansible.

**Comment by ayoustic** [comment]
@anupamaloke Thanks for your help. I did not see a clear indicator in the documentation that I read [here](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/idrac_redfish_storage_controller.rst)

Did I miss something or is there something that should be clarified in the docs for this?

**Comment by anupamaloke** [comment]
@ayoustic, I am closing this issue. In the NOTES section within the module documentation, it mentions that the module is only supported on iDRAC9.
