### ISSUE TITLE
[QUESTION]: Reset iDrac to defaults

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#464]
Hello,  is there any module ( current or planned ) which would allow to reset iDrac to defaults ?

API: 
/redfish/v1/Managers/<ID>/Actions/Oem/DellManager.ResetToDefaults

**Comment by sachin-apa** [comment]
@markatdxb the feature is added incollection as part of the role `idrac_reset, more details [here](https://github.com/dell/dellemc-openmanage-ansible-modules/tree/collections/roles/idrac_reset)

Closing the issue with an information.
