### ISSUE TITLE
[BUG]: Upgrade from HTTP with proxy support

### ISSUE THREAD

**Issue by Mixer9** [dell/dellemc-openmanage-ansible-modules#467]
### Bug Description

When attempting to use idrac_firmware via proxy I receive an error stating "msg": "update_from_dell_repo_url() got an unexpected keyword argument 'proxy_support'"} 

### Component or Module Name

idrac_firmware

### Ansible Version

ansible [core 2.13.3]

### Python Version

python version = 3.9.14

### iDRAC/OME/OME-M version

iDRAC 2.75.100.75

### Operating System

Red Hat Enterprise Linux release 9.1 (Plow)

######################################################
# Description:
# Author: Chris Hood
# Last Modified
######################################################
---

- name:
  hosts: all
  gather_facts: no
  become: yes
  vars:
    drac_user: root
    drac_ip: 0.0.0.0 
    drac_passwd: password 

  collections:
    - dellemc.openmanage

  tasks:

    - name: Set primary DNS server
      idrac_attributes:
        idrac_ip: "{{ drac_ip }}"
        idrac_user: "{{ drac_user }}"
        idrac_password: "{{ drac_passwd }}"
        validate_certs: False
        idrac_attributes:
          IPv4Static.1.DNS1: "0.0.0.0"

    - name: Update firmware from repository on a HTTP
      idrac_firmware:
        idrac_ip: "{{ drac_ip }}"
        idrac_user: "{{ drac_user }}"
        idrac_password: "{{ drac_passwd }}"
        share_name: "https://downloads.dell.com/catalog"
        reboot: True
        job_wait: True
        apply_update: True
        validate_certs: False
        proxy_support: ParametersProxy
        proxy_server: 0.0.0.0
        proxy_port: 9290
        proxy_type: HTTP
      register: output

    - name: Spit out returned message
      debug:
        msg: "output is {{ output.msg }}"

### Logs

TASK [Update firmware from repository on a HTTP] *****************************************************************************************************************************
task path: /home/user/development/ops/redhat/ansible/rh_update_iDRAC.yml:45
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-wit
h-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' localhost '/bin/sh -c '"'"'e
cho ~ && sleep 0'"'"''
<localhost> (0, b'/home/user\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-wit
h-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' localhost '/bin/sh -c '"'"'(
 umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465 `" && echo ansibl
e-tmp-1674503784.1867194-354805-246028527148465="` echo /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1674503784.1867194-354805-246028527148465=/home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465\n', b'')
Using module file /home/user/.ansible/collections/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-354433npoxd6c_/tmp2szffabm TO /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465/Ansiba
llZ_idrac_firmware.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssa
pi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' '[localhost]'
<localhost> (0, b'sftp> put /home/user/.ansible/tmp/ansible-local-354433npoxd6c_/tmp2szffabm /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-2460285271484
65/AnsiballZ_idrac_firmware.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-wit
h-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' localhost '/bin/sh -c '"'"'c
hmod u+x /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465/ /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465/An
siballZ_idrac_firmware.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-wit
h-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' -tt localhost '/bin/sh -c '"
'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dnculaicjvaytfwiueuhrgzmrbvruxmu ; /usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-167450378
4.1867194-354805-246028527148465/AnsiballZ_idrac_firmware.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<localhost> (1, b'\r\n{"failed": true, "msg": "update_from_dell_repo_url() got an unexpected keyword argument \'proxy_support\'", "exception": "  File \\"/tmp/ansible_idrac_f
irmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py\\", line 785, in main\\n  File \\"/tmp/an
sible_idrac_firmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py\\", line 551, in update_firm
ware_omsdk\\n  File \\"/tmp/ansible_idrac_firmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.p
y\\", line 513, in update_firmware_url_omsdk\\n", "invocation": {"module_args": {"idrac_ip": "0.0.0.0", "idrac_user": "root", "idrac_password": "VALUE_SPECIFIED_IN_NO_L
OG_PARAMETER", "share_name": "https://downloads.dell.com/catalog", "reboot": true, "job_wait": true, "apply_update": true, "validate_certs": false, "proxy_support": "ParametersProxy", "proxy_server": "1.1.1.1", "proxy_port": 9290, "proxy_type": "HTTP", "catalog_file_name": "Catalog.xml", "ignore_cert_warning": true, "idrac_port": 443, "timeout": 30, "share_user": null, "share_password": null, "share_mnt": null, "proxy_uname": null, "proxy_passwd": null, "ca_path": null}}}\r\n', b'Shared connection to localhost closed.\r\n')
<localhost> Failed to connect to the host via ssh: Shared connection to localhost closed.
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 -o 'ControlPath="/home/user/.ansible/cp/8a5a4c6a60"' localhost '/bin/sh -c '"'"'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1674503784.1867194-354805-246028527148465/ > /dev/null 2>&1 && sleep 0'"'"''
<localhost> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_idrac_firmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py", line 785, in main
  File "/tmp/ansible_idrac_firmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py", line 551, in update_firmware_omsdk
  File "/tmp/ansible_idrac_firmware_payload_arv64t0n/ansible_idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py", line 513, in update_firmware_url_omsdk
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "apply_update": true,
            "ca_path": null,
            "catalog_file_name": "Catalog.xml",
            "idrac_ip": "0.0.0.0",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "ignore_cert_warning": true,
            "job_wait": true,
            "proxy_passwd": null,
            "proxy_port": 9290,
            "proxy_server": "1.1.1.1",
            "proxy_support": "ParametersProxy",
            "proxy_type": "HTTP",
            "proxy_uname": null,
            "reboot": true,
            "share_mnt": null,
            "share_name": "https://downloads.dell.com/catalog",
            "share_password": null,
            "share_user": null,
            "timeout": 30,
            "validate_certs": false
        }
    },
    "msg": "update_from_dell_repo_url() got an unexpected keyword argument 'proxy_support'"
}

### Steps to Reproduce

run the playbook against an iDRAC version 8 using the proxy settings in idrac_firmware module

### Expected Behavior

I expect it to run without error and update the system

### Actual Behavior

fatal: [localhost]: FAILED! => {"changed": false, "msg": "update_from_dell_repo_url() got an unexpected keyword argument 'proxy_support'"}

**Comment by sachin-apa** [comment]
@Mixer9 Can you please update the **omsdk** library to the latest version and retry the operation.

**Comment by anupamaloke** [comment]
@Mixer9, I am closing this issue. If you are running into this issue even after upgrading to latest `omsdk` library, please reopen the issue or raise a new ticket.

**Comment by Mixer9** [comment]
Thank you very much. I think that the issue is fixed.

Mixer9
