### ISSUE TITLE
[BUG]: idrac_attributes failing regularly

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#471]
### Bug Description

i have automated process to update several LC attributes - see example below which regularly fails on first run. unfortunately its a fatal failure so retry process doesnt work
seems that this module is pretty unstable / unreliable as its part of the playbook with other dell modules which work just fine

### Component or Module Name

idrac_attributes

### Ansible Version

Ansible 2.13.4

### Python Version

Python 3.9.6

### iDRAC/OME/OME-M version

idrac8 2.83.83.83

### Operating System

happens on any OS

### Playbook Used

 - name: Configure specific iDrac attributes
      dellemc.openmanage.idrac_attributes:
        idrac_ip: "{{ lom_ip }}"
        idrac_user: "{{ lom_username }}"
        idrac_password: "{{ lom_password }}"
        validate_certs: false
        idrac_attributes:
          NIC.1.DNSRacName: "{{ lom_hostname }}"
          ADGroup.3.Name: "{{ site_grp_name | default('') }}"
          ADGroup.3.Domain: "{{ site_grp_domain | default('') }}"
          ADGroup.3.Privilege: "{{ site_grp_priv | default(0) }}"
          ADGroup.4.Name: "{{ sql_grp_name | default('') }}"
          ADGroup.4.Domain: "{{ sql_grp_domain | default('') }}"
          ADGroup.4.Privilege: "{{ sql_grp_priv | default(0) }}"
          ADGroup.5.Name: "{{ biz_grp_name | default('') }}"
          ADGroup.5.Domain: "{{ biz_grp_domain | default('') }}"
          ADGroup.5.Privilege: "{{ biz_grp_priv | default(0) }}"
        timeout: 120
      register: imp_profile_cust
      until: imp_profile_cust is success
      delay: 60

### Logs

sometime i get 
urlopen error EOF occurred in violation of protocol (_ssl.c:1129)

sometime:
urlopen error Tunnel connection failed: 504 Gateway Timeout

### Steps to Reproduce

standard playbook as mentioned above

### Expected Behavior

set attributes without module error

### Actual Behavior

fatal module crash

**Comment by markatdxb** [comment]
again the same error - urlopen error Tunnel connection failed: 504 Gateway Timeout 
interesting is that when i re-run the same playbook again, most of the time it works ok 
do i need to split idrac name change and other changes into 2 tasks ?

**Comment by markatdxb** [comment]
hello again - "msg": "urlopen error _ssl.c:1112: The handshake operation timed out", 
any advice on how to fix all these issues ? that module is pretty unusable in this condition

**Comment by anupamaloke** [comment]
Hi @markatdxb, any chance you could open a Support Ticket for this issue?  We might have to get support team involved to see whether there is an underlying issue with iDRAC itself.

**Comment by markatdxb** [comment]
@anupamaloke   i have this module implemented as part of the iDrac onboarding process with many other Dell modules in the same playbook.. So the issue is not related to specific iDrac but the module as other modules work just fine. 
Also when i re-run that process on iDrac where it previously failed, it usually succeed on the second or third attempt.

**Comment by anupamaloke** [comment]
@markatdxb, thank you for sharing your observation. 

> again the same error - urlopen error Tunnel connection failed: 504 Gateway Timeout
interesting is that when i re-run the same playbook again, most of the time it works ok
do i need to split idrac name change and other changes into 2 tasks ?

We will check it again on our end and come back. For now, could you please share your observation when you split these into two separate tasks?

**Comment by anupamaloke** [comment]
@markatdxb, could you also please drop us an email at OpenManageAnsible@dell.com regarding this issue?

**Comment by anupamaloke** [comment]
@markatdxb, checking to see whether you are still running into this issue.

**Comment by anupamaloke** [comment]
@markatdxb, I am closing this ticket. Please reopen or raise a new ticket if you are still running into an issue.
