### ISSUE TITLE
[QUESTION]: Select only components with no reboot required

### ISSUE THREAD

**Issue by benboreham** [dell/dellemc-openmanage-ansible-modules#472]
In OME when creating a baseline there is an option to "Select only components with no reboot required"

Is this feature accessible via the API?

![image](https://user-images.githubusercontent.com/99457184/218372029-a7a2c101-9c14-4d0e-9e36-fd433f40657f.png)

**Comment by sachin-apa** [comment]
Closing the issue as this is fixed with PR # [512](https://github.com/dell/dellemc-openmanage-ansible-modules/pull/512) Release 8.1.0
