### ISSUE TITLE
[FEATURE]: module idrac_firmware allow_downgrade/force_downgrade

### ISSUE THREAD

**Issue by jeroenhuisman** [dell/dellemc-openmanage-ansible-modules#473]
**Describe the solution you'd like**
Currently the module idrac_firmware does not allow firmware to be downgraded.
In large scale deployments with very specific firmware requirements it is often necessary to downgrade the firmware.
This can currently only be done when the servers in question have already been added to OpenManage Enterprise and using OpenManage Enterprise to force firmware downgrade.
Deployments can be sped up and automated significantly if the ansible module idrac_firmware will allow downgrade of firmware.

**Describe alternatives you've considered**
No other alternatives available other than using OpenManage Enterprise separately to downgrade the firmware before finishing the configuration of the servers using sensible.

**Additional context**
This functionality will be extremely beneficial for large scale deployments with specific firmware requirements.

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@jeroenhuisman, thank you for submitting the feature request. This is already on our backlog and will be priortized for upcoming future releases.

**Comment by anupamaloke** [comment]
@jeroenhuisman, the firmware rollback support has been added as part of #519. Closing this as completed.
