### ISSUE TITLE
[FEATURE]: Make ome_inventory module options available via environment variables

### ISSUE THREAD

**Issue by zigford** [dell/dellemc-openmanage-ansible-modules#480]
dellemc.openmanage.ome_inventory hostname, password, port parameters should be able to be set via environment variables rather than parameters to the dynamic inventory. This allows their use in a secure environment like AWX without having to store the values in plain text in the inventory file.

Alternatives:
I've read that ansible can support extra-vars to a dynamic inventory file, but that the inventory file needs to support it.

Having the values available through environment variables also allows an inventory to be configured generically, and simply running it under a different environment can connect to a different ome without needing a seperate inventory file.

**Comment by sachin-apa** [comment]
@zigford  Thanks for requesting a feature enhancement.
Env variable is something we have to enhance in the plugin, do please let us know if you are interested in submitting the PR for the same?
I do see when we pass -e(extra var) argument the same gets added into all the hosts. `-e "key=value"`

@anupamaloke

**Comment by zigford** [comment]
@sachin-apa, I have a PR in the waiting, but I'm just completing unit tests before submission.
I did test the -e "key=value" method, but it seems the inventory plugin has to support it. I can look at adding that too.

**Comment by sachin-apa** [comment]
Merged the PR
