### ISSUE TITLE
[FEATURE]: Detailed Job information needs to add in OME Discovery and Job Info Module 

### ISSUE THREAD

**Issue by arunakumari16** [dell/dellemc-openmanage-ansible-modules#484]
Please add the feature to get detailed Job information (like reason for failed devices) from OME discovery and Job Information Module.

OME Discovery Module:   **"dellemc.openmanage.ome_discovery"** 
OME Jog info Module:      **dellemc.openmanage.ome_job_info**

Please consider this as priority and do the needful as its one of the client requirements.

**Comment by anupamaloke** [comment]
@arunakumari16, thank you for submitting the feature request. We will accrodingly triage and prioritize it for future releases.

**Comment by sachin-apa** [comment]
Closing the issue as this is fixed with PR # [512](https://github.com/dell/dellemc-openmanage-ansible-modules/pull/512) Release 8.1.0
