### ISSUE TITLE
[QUESTION]: import cert to idrac

### ISSUE THREAD

**Issue by t4chy** [dell/dellemc-openmanage-ansible-modules#485]
Hey guys.

I followed the examples from [docs.ansible.com/ansible/latest/collections/dellemc/openmanage/idrac_certificates_module.html](url), but i dont get it, in which format the cert files have to be.

I tried a pem file with key, cert
I tried a pem file with key, cert, intermediate, root
I tried both in a base64 encoded way. (cat bla.pem > bla.pem64)
I tried a p12 file with key, cert
I tried a p12 file with key, cert, intermediate, root

I tried all the above with certificate_type HTTPS, CA, CSC

Nothing works. I either get the warning in idrac "Unable to import the CUSTOM SIGNED CERT certificate, because either the certificate is invalid, expired, or has a key mismatch issue." Key and cert fit each other for sure.

Or i get an error message from ansible-playbook: 

shortened:

Message": "Certificate import operation failed
"A general error has occurred. See ExtendedInfo for more information"}}, "msg": "HTTP Error 400: Bad Request"}

----------------

`fatal: [ -> localhost]: FAILED! => {
    "changed": false,
    "error_info": {
        "error": {
            "@Message.ExtendedInfo": [
                {
                    "Message": "Certificate import operation failed.",
                    "MessageArgs": [
                        ""
                    ],
                    "MessageArgs@odata.count": 1,
                    "MessageId": "IDRAC.2.8.LC011",
                    "RelatedProperties": [],
                    "RelatedProperties@odata.count": 0,
                    "Resolution": "Do the following and retry the operation: 1) WS-Man: Rerun the command or reset the iDRAC by invoking the iDRACReset method which is defined in the DCIM_iDRACCardService class. 2) iDRAC GUI: Restart the iDRAC.",
                    "Severity": "Critical"
                }
            ],
            "code": "Base.1.12.GeneralError",
            "message": "A general error has occurred. See ExtendedInfo for more information"
        }
    },
    "msg": "HTTP Error 400: Bad Request"
`

----------------

When i create a p12 file with key, cert, intermediate and root cert and upload it via the webgui, it's working absolutely fine.

I have literally no idea what else to do.

Remote idrac has fw version: 6.10.30.00

**Comment by sachin-apa** [comment]
@t4chy I did try the module here, below is the playbook and it seems to be working fine. certificate should be `base64` encoded `.pem` format for iDRAC to import.
```
- name: Import a HTTPS certificate.
  dellemc.openmanage.idrac_certificates:
    idrac_ip: "{{ hostname }}"
    idrac_user: "{{ username }}"
    idrac_password: "{{ password }}"
    validate_certs: false
    command: "import"
    certificate_type: "HTTPS"
    certificate_path: "/root/certificates/certnew.pem"
```
Also, the error message you are seeing is from IDRAC, Did you try restarting an iDRAC ?

Since certificate is a sensitive data, you might need to open a service ticket to connect with dell team and debug further.
@anupamaloke

**Comment by ShivamSh3** [comment]
When I was trying to import a HTTPS certificate, it was showing me the same error as above. I resolved it by regenerating the CSR and imported the self-signed certificate.

**Comment by t4chy** [comment]
Yeah, it gives me the impression that its not possible to import a company CA signed cert via ansible.

I generated a csr outside of idrac, requested a cert from our CA and created a pem file with key, cert, intermediate, root. Not a single certificate_type works with this pem file. All base64 encoded.

Importing via idrac gui works very well. But the whole file with key, cert, inter and root are in p12 format then.

It seems, as if its not possible to import certs while the csr was generated outside of idrac. I mean, priv keys in .pem files is pretty normal.

**Comment by tazend** [comment]
Hi,

I'm also trying to import a company CA signed certificate with ansible.
Tried it on two different servers, on has 6.10.30.00 idrac firmware, the other one 5.10.50.00

On the server with 5.10.50.00, I receive the exact same error as @t4chy from the playbook.
On the other one with 6.10.30.00, its a bit different:

```
    "changed": false,
    "error_info": {
        "error": {
            "@Message.ExtendedInfo": [
                {
                    "@odata.type": "#Message.v1_1_0.Message",
                    "Description": "Indicates that query is not supported on the implementation.",
                    "Message": "Querying is not supported by the implementation.",
                    "MessageId": "Base.1.8.QueryNotSupported",
                    "Resolution": "Remove the query parameters and resubmit the request if the operation failed.",
                    "Severity": "Warning"
                }
            ],
            "code": "Base.1.8.GeneralError",
            "message": "A general error has occurred. See ExtendedInfo for more information."
        }
    }
}

MSG:

HTTP Error 400: Bad Request
```

Literally also tried all options - explicitly base64 encoded, plain p12 (which will automatically be encoded to base64 [by the module](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/plugins/modules/idrac_certificates.py#L307) anyway it seems), non-password protected...nothing works though.

**Comment by anupamaloke** [comment]
@t4chy, @tazend, could you please try using the following role and let us know whether you are able to import the company CA signed certificate: [idrac_install_ssl_certificate_wsman](https://github.com/dell/redfish-ansible-module/tree/master/roles/idrac_install_ssl_certificate_wsman)

**idrac1.yml**
```
---
ansible_user: root
idrac_address: 10.113.0.46
idrac_user: root
idrac_user_password: calvin
idrac_https_port: 443
ca_cert_file: "./test_files/root-ca.pem"
certificate_file: "./test_files/signed-certificate.pem"
privatekey_file: "./test_files/private-key.pem"
certificate_format: "PEM"
```

**hosts**
```
idrac1
```

**main.yml**
```
---

- name: manage SSL certificate
  hosts: all
  gather_facts: no
  tasks:
    - name: "Include idrac_manage_ssl_certificate_wsman"
      include_role:
        name: "idrac_manage_ssl_certificate_wsman"
```

**Comment by anupamaloke** [comment]
@t4chy, @tazend,  just checking on whether you were able to use the role?

**Comment by t4chy** [comment]
> @t4chy, @tazend, just checking on whether you were able to use the role?

i'll check it out during the week.

**Comment by tazend** [comment]
> @t4chy, @tazend, just checking on whether you were able to use the role?

Hi, sorry, haven't been able to check it out yet. I'll try to do so this week.
