### ISSUE TITLE
[FEATURE]: ome_application_certificate support Subject Alternative Names

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#487]
**Describe the solution you'd like**
In the GUI, when doing Generate Certificate Signing Request, there are optional fields for Subject Alternative Names, up to 4 of them.  The module `ome_application_certificate` does not have support for these fields

**Describe alternatives you've considered**
Manually generate the CSR and then upload with resulting cert with the Ansible module

**Additional context**
I use a VIP for my OME-M environment, so if I use the Ansible module using the VIP name, it does not also include the chassis DNS name.  DellGroup1.domain.com for the VIP but also need to add DellGroup1Chassis1.domain.com for the actual Chassis that is currently the Lead

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@MallocArray, thank you for submitting the feature request. I have added it to the backlog and we will accordingly prioritize it for our future releases.

**Comment by sachin-apa** [comment]
Closing the issue as this is fixed with PR # [512](https://github.com/dell/dellemc-openmanage-ansible-modules/pull/512) Release 8.1.0
