### ISSUE TITLE
The error was: KeyError: 'idrac_password'

### ISSUE THREAD

**Issue by richardjohnallsopp** [dell/dellemc-openmanage-ansible-modules#49]
Hey all,

I'm trying to build some Ansible playbooks to configure iDrac moving forward and I can't seem to get the dellemc_get_system_inventory to work. It keeps failing with the following:

_An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'idrac_password'
fatal: [test_server]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1558458853.37-38202877671688/AnsiballZ_dellemc_get_system_inventory.py", line 114, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1558458853.37-38202877671688/AnsiballZ_dellemc_get_system_inventory.py", line 106, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1558458853.37-38202877671688/AnsiballZ_dellemc_get_system_inventory.py", line 49, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "/tmp/ansible_dellemc_get_system_inventory_payload_bmfmxr/__main__.py", line 115, in <module>
      File "/tmp/ansible_dellemc_get_system_inventory_payload_bmfmxr/__main__.py", line 104, in main
      File "/tmp/ansible_dellemc_get_system_inventory_payload_bmfmxr/ansible_dellemc_get_system_inventory_payload.zip/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py", line 35, in __init__
    KeyError: 'idrac_password'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1_

In case you need it my BIOS and iDrac version are:
BIOS Version | 1.6.13
-- | --
iDRAC Firmware Version | 3.30.30.30

ansible --version = ansible 2.8.0

I'm not sure why it's failing here -  KeyError: 'idrac_password'. I know the password is correct as I can CURL to the box from this host.

Rich

**Comment by anupamaloke** [comment]
@richardjohnallsopp, it is an issue that we are going to be fixing. The issue manifests because in ansible v2.8.0, the module argument ```idrac_pwd``` was renamed to ```idrac_password``` in the [dellemc_idrac.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py) util file. In the meantime, you can use the following workaround to fix this:

- on your ansible installation, edit```/usr/lib/python2.7/site-packages/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py``` ; If running python3.x, then change the file path accordingly
- On line#35, change ```module_params['idrac_password']``` to ```module_params['idrac_pwd']```
- save and close the file.
- Run the playbook again and verify that you do not run into the same ```KeyError: 'idrac_password'```

**Comment by anupamaloke** [comment]
@richardjohnallsopp, this issue has now been fixed. Please pull in the latest omsdk repo and re-install it. Let us know if you still face this.

**Comment by richardjohnallsopp** [comment]
Yup that resolved my issue, thanks so much :-)

**Comment by jb185t** [comment]
Thanks for the resolution. It worked for me too!

Python3 path to the dellemc_idrac.py;

/usr/local/lib/python3.6/dist-packages/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py

**Comment by richardjohnallsopp** [comment]
Has there been a regression in this bug when using ansible 2.9 for some reason all my playbooks are failing since the upgrade. Happy to open a new issue if you feel it's needed.

**Comment by richardjohnallsopp** [comment]
Has there been a regression in this bug when using ansible 2.9 for some reason all my playbooks are failing since the upgrade. Happy to open a new issue if you feel it's needed.

**Comment by GreyGnome** [comment]
This is still an issue for me with the latest dellemc-openmanage-ansible-modules (downloaded today 2020 05 18) and with ansible 2.9.1. This time, I needed to edit line 33, and make it look like this:

`self.idrac_pwd` = module_params['idrac_pwd']`

If I try to use "idrac_password" in my Ansible YML file, the system will complain that it's an unsupported parameter, and I need to use idrac_pwd:

`Supported parameters include: command, end_host_power_state, export_format, export_use, idrac_ip, idrac_port, idrac_pwd`

**Comment by robertpriedl** [comment]
For me, this is also an issue with the latest dellemc-openmanage-ansible-modules (downloaded yesterday 2020 06 05)
The module_params on line 33 have to be changed from idrac_password to idrac_pwd.
