### ISSUE TITLE
[QUESTION]:msg: Dell OMSDK library is required for this module

### ISSUE THREAD

**Issue by perezm25** [dell/dellemc-openmanage-ansible-modules#498]
### How can the team help?
We had created an ansible script with Docker containers to streamline the process of updating firmware on our lab servers from the Dell repository. However, we have encountered an issue that I wanted to bring to your attention. When executing our playbook titled "main.yml," we are consistently facing the error message stating that the "Dell OMSDK library is required for this module."

**Details: ?**

Python version:

rmcyc-perezm25-1-00:/dell_firmware # python --version
Python 3.9.16

Ansible version:

drmcyc-perezm25-1-00:/dell_firmware # ansible --version
ansible [core 2.14.5]
  config file = /dell_firmware/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Dec 09 2022, 12:16:57) [GCC] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

Error Messages:

root@drmcyc-perezm25-1-00:/home/cyc/playbooks/dell_firmware (development)# docker-compose run -e hosts="BMCIP" --rm dell_firmware ansible-playbook  main.yml -vvv -e idrac_username=BMCuser -e idrac_password=BMCpassword
ansible-playbook [core 2.14.5]
  config file = /dell_firmware/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.16 (main, Dec 09 2022, 12:16:57) [GCC] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
Using /dell_firmware/ansible.cfg as config file
host_list declined parsing /dell_firmware/inventory.py as it did not pass its verify_file() method
Parsed /dell_firmware/inventory.py inventory source with script plugin
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: main.yml ***************************************************************************************************************************************************************************************************************
1 plays in main.yml

PLAY [LGS] ***********************************************************************************************************************************************************************************************************************

TASK [Clear Lifecycle Controller job queue] **************************************************************************************************************************************************************************************
task path: /dell_firmware/main.yml:10
<BMCIP> ESTABLISH LOCAL CONNECTION FOR USER: root
<BMCIP> EXEC /bin/sh -c 'echo ~root && sleep 0'
<BMCIP> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368 `" && echo ansible-tmp-1684783931.2608604-13-155432160317368="` echo /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/dellemc/openmanage/plugins/modules/idrac_lifecycle_controller_jobs.py
<BMCIP> PUT /root/.ansible/tmp/ansible-local-7orm80_vc/tmpiin_0zyz TO /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368/AnsiballZ_idrac_lifecycle_controller_jobs.py
<BMCIP> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368/ /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368/AnsiballZ_idrac_lifecycle_controller_jobs.py && sleep 0'
<BMCIP> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368/AnsiballZ_idrac_lifecycle_controller_jobs.py && sleep 0'
<BMCIP> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1684783931.2608604-13-155432160317368/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_dellemc.openmanage.idrac_lifecycle_controller_jobs_payload_ukrdz9s_/ansible_dellemc.openmanage.idrac_lifecycle_controller_jobs_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_lifecycle_controller_jobs.py", line 114, in main
  File "/tmp/ansible_dellemc.openmanage.idrac_lifecycle_controller_jobs_payload_ukrdz9s_/ansible_dellemc.openmanage.idrac_lifecycle_controller_jobs_payload.zip/ansible_collections/dellemc/openmanage/plugins/module_utils/dellemc_idrac.py", line 58, in __init__
    raise ImportError("Dell OMSDK library is required for this module")
fatal: [BMCIP]: FAILED! => changed=false
  invocation:
    module_args:
      ca_path: null
      idrac_ip: BMCIP
      idrac_password: ''
      idrac_port: 443
      idrac_user: BMCuser
      job_id: null
      timeout: 30
      validate_certs: false
  msg: Dell OMSDK library is required for this module

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
BMCIP             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by MallocArray** [comment]
Did you install the module inside of your container image?  I had one recent build of my Execution Environment that wasn't loading this module correctly, but I built the image again a few days later and then it behaved as expected.

For a manual install, you can do
`pip3 install OMSDK`

**Comment by perezm25** [comment]
yes I did. I fixed with this workaround https://github.com/dell/omsdk/issues/33

Run pip install “urllib3>=1.26.14,<2.0” before installing omsdk.
