### ISSUE TITLE
[FEATURE]: Add reboot options to module dellemc.openmanage.ome_firmware

### ISSUE THREAD

**Issue by sbeyermann** [dell/dellemc-openmanage-ansible-modules#505]
**Describe the solution you'd like**
Most firmware updates require a reboot. When the ansible module `dellemc.openmanage.ome_firmware` is used to update firmware, it is possible to use the `schedule` parameter to schedule the necessary reboot to `RebootNow` or `StageForNextReboot`. However when `RebootNow` is used, I have not found a way to specify the type of reboot.

In the Dell OpenManage Enterprise web interface there are three different types of immediate reboots in the "Device Compliance Dialog":
- Graceful Reboot with Forced Shutdown
- Graceful Reboot without Forced Shutdown
- Power Cycle

For me it currently looks like "Power Cycle" is always used when `RebootNow` is selected as the firmware update schedule. It would be great if the `dellemc.openmanage.ome_firmware module` enabled the users to select which type of reboot they would prefer in their ansible scripts.

**Describe alternatives you've considered**
If a graceful reboot should be achieved, the `schedule` parameter could be set to `StageForNextReboot` and another task added to the playbook in which the target system is rebooted with the `ansible.builtin.reboot` module. However for this to work, credentials for the target system are required whereas the `dellemc.openmanage.ome_firmware` module only requires credentials for Dell OpenManage Enterprise.

**Additional context**
Maybe I am wrong and the default reboot type is not `power cycle` or the reboot type can be specified. I would appreciate an according feedback.

**Community Note**
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@sbeyermann , sorry for delayed response. This has been added to the backlog and will be accordingly prioritized for future releases.
