### ISSUE TITLE
Firmware Ansible Playbook

### ISSUE THREAD

**Issue by rajganeshsekar12** [dell/dellemc-openmanage-ansible-modules#510]
--> We are trying to update firmware via ansible play for iDRAC Server IPv6 . 
       firmware.exec file is from the local artifactory FYR.
       we are facing an error stating that. 
      "Resolution": "Execute InstallFromRepo method, and then retry the operation."
 
--> we are blocked with catalog XML file as to construct as well. While we are trying to construct the catalog using the module 
      dellemc.openmanage.ome_firmware_catalog -->  Not Supported IPv6

Tuesday 04 July 2023  13:25:20 +0000 (0:00:00.051)       0:00:00.051 **********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "invalid literal for int() with base 10: 'fbc'"}
 
**--> Modules we are using :** 
- dellemc.openmanage.redfish_firmware -->  Not supported IPv6
- dellemc.openmanage.ome_firmware_catalog --> Not Supported IPv6
- dellemc.openmanage.idrac_firmware_info --> Supported IPv6
- dellemc.openmanage.idrac_firmware --> Supported IPv6

**Sample playbook :**
tasks:
    - name: Update firmware from repository on a HTTP
      dellemc.openmanage.idrac_firmware:
        idrac_ip: "<ipv6>"
        idrac_user: "root"
        idrac_password: "calvin"
        validate_certs: False
        catalog_file_name: "/data/tasks/Catalog.xml"
        share_name: “<IPv6>”
        reboot: True
        job_wait: True
        apply_update: True
 
 
**TASK [Update firmware from repository on a HTTP]** *************************************************************************************************
Tuesday 04 July 2023  13:11:43 +0000 (0:00:00.055)       0:00:00.055 **********
fatal: [localhost]: FAILED! => {"changed": false, "msg": {"error": {"@Message.ExtendedInfo": [{"Message": "The GetRepoBasedUpdateList method did not complete successfully.", "MessageArgs": [], [MessageArgs@odata.count](mailto:MessageArgs@odata.count): 0, "MessageId": "IDRAC.2.5.SUP028", "RelatedProperties": [], [RelatedProperties@odata.count](mailto:RelatedProperties@odata.count): 0, "Resolution": "Execute InstallFromRepo method, and then retry the operation.", "Severity": "Warning"}], "code": "Base.1.8.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information"}}}

Can someone please help us here

**Comment by anupamaloke** [comment]
@rajganeshsekar12, could you please share the playbook including the argument variables (you can substitute the actual info with an example one, for e.g. 2001:db8:85a3:8d3:1319:8a2e:370:7348)?
