### ISSUE TITLE
Error regarding share path for network boot

### ISSUE THREAD

**Issue by richardjohnallsopp** [dell/dellemc-openmanage-ansible-modules#53]
Hey all,

I'm seeing an issue with trying to boot my idrac machine from a network boot iso. I've mounted the windows share containing the iso correctly and can access the iso from within via the ansible box. However, when I run the playbook pointing to the share and iso I see the error bellow:

flynn@ncl-ansible-01:~/ansible/playbooks/idrac$ ansible-playbook dell_idrac.yml --tags "network_iso" -i inventory_dell_idrac

PLAY [idrac_servers] *******************************************************************************************************************************************************************************************

TASK [install_esx_custom_image : Install esx esx-6-0u3.iso] ****************************************************************************************************************************************************
fatal: [10.29.50.3]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  msg: 'Error: Share path is not valid : ''/home/flynn/ansible/iso/esx_6_0_u3_custom.iso'''

PLAY RECAP *****************************************************************************************************************************************************************************************************
10.29.50.3                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

flynn@ncl-ansible-01:~/ansible/playbooks/idrac$ ls /home/flynn/ansible/iso/
esx_6_0_u3_custom.iso  ks.cfg
flynn@ncl-ansible-01:~/ansible/playbooks/idrac$

Am I missing something, or is there an error in the back end?

Rich

**Comment by anupamaloke** [comment]
@richardjohnallsopp, could you please share the playbook? Also, you need to make sure that ISO is accessible from iDRAC. The module basically tells iDRAC to download the ISO from the network path.

**Comment by richardjohnallsopp** [comment]
@anupamaloke,

Sure here is the role:

---
# tasks file for install_esx_custom_image

  - name: "Install esx esx-6-0u3.iso"
    dellemc_boot_to_network_iso: 
     idrac_ip:   "{{ host }}"
     idrac_user: "{{ idrac_user }}"
     idrac_pwd:  "{{ idrac_password }}"
     share_name: "/home/flynn/ansible/iso"
     iso_image: "esx_6_0_u3_custom.iso"
    tags:
     - network_iso

I use the same cifs share mounted to the same Ansible box to upload ESX templates so I know it works and there is nothing blocking the iDrac from hitting it from a networking level.

Rich

**Comment by anupamaloke** [comment]
@richardjohnallsopp, sorry for a delayed response. I believe you need to provide the actual CIFS share path and not the mounted path in 'share_name', as below. The module just tells iDRAC to download the ISO image from the CIFS share path.

```
share_name: "\\\\192.168.10.10\\iso" ## here 192.168.10.10 is the IP address of CIFS share that is accessible from iDRAC
iso_image:  "esx_6_0_u3_custom.iso"
```

**Comment by richardjohnallsopp** [comment]
Hey thanks for that, you're correct and that did get past the error :-)
