### ISSUE TITLE
[BUG]: ome_device_quick_deploy does not assign slot static IP if blade is not present

### ISSUE THREAD

**Issue by jason-technology** [dell/dellemc-openmanage-ansible-modules#532]
### Bug Description

if blade is not present, the following error is shown.
"changed": false, "msg": "'VlanId'"
This happens regardless of what the VlanID settings are.

Quick Deploy IP addresses should be able to be set without a blade present.

### Component or Module Name

ome_device_quick_deploy

### Ansible Version

2.15.2

### Python Version

Python 3.10.12

### iDRAC/OME/OME-M version

OME-M 2.10.10

### Operating System

Ubuntu 22.04.3 LTS

### Playbook Used

- hosts: MX7000ChassisSlots
  connection: local
  gather_facts: false
  name: Chassis Slot Operations

  tasks:
    - name: Configure Slot Quick Deploy settings
      dellemc.openmanage.ome_device_quick_deploy:
        hostname: "{{ hostvars['OMEModular']['ome_ip'] }}"
        username: "{{ hostvars['OMEModular']['ome_login'] }}"
        password: "{{ hostvars['OMEModular']['ome_password'] }}"
        validate_certs: false
        device_service_tag: "{{ parent_chassis }}"
        setting_type: ServerQuickDeploy
        quick_deploy_options:
          # password: "{{ quick_password }}"
          ipv4_enabled: true
          ipv4_network_type: Static
          ipv4_subnet_mask: "{{ quick_netmask }}"
          ipv4_gateway: "{{ quick_gateway }}"
          ipv6_enabled: false
          ipv6_network_type: Static
          ipv6_prefix_length: 64
          ipv6_gateway: "::"
          slots:
            - slot_id: "{{ slot_id }}"
              slot_ipv4_address: "{{ quick_ip }}"
              slot_ipv6_address: "::"
      register: quick_slot_output
      tags:
        - quick_slot_setup

    - name: Debug Slot Quick Deploy
      ansible.builtin.debug:
        var: quick_slot_output
      tags:
        - quick_slot_setup_debug

### Logs

.

### Steps to Reproduce

Run the playbook

### Expected Behavior

slot configured

### Actual Behavior

slot not configured, error

**Comment by sachin-apa** [comment]
This is Fixed as part of the Releases 8.3.0

**Comment by sachin-apa** [comment]
There was a confusion and the PR was closed without merging a fix, the later changes was to handle idempotent scenario. Reopening this defect to fix in releases 8.4.0
