### ISSUE TITLE
inventory plugin is only resturning 50 results per group

### ISSUE THREAD

**Issue by tallyoh** [dell/dellemc-openmanage-ansible-modules#547]
Hello,

I am using the ome_inventory plugin for ansible and I am only able to receive 50 results, and only if I specify a group. Without a group created in ome, I actually dont get any results at all. Has anyone encountered this issue before? Any solutiuon?

Thanks in advance.

**Comment by anupamaloke** [comment]
@tallyoh, could you please let us know the version of the openmanage collection that you are using?

**Comment by sachin-apa** [comment]
@tallyoh I have a fix for this attached please replace and let me know if it is good, please feel free to submit a PR for the fix.
[ome_inventory.zip](https://github.com/dell/dellemc-openmanage-ansible-modules/files/12812193/ome_inventory.zip)

**Comment by DellDavidMcKay** [comment]
I gave this a try, it did not return anymore results than the old version. I still get the top 50. I have over 400 blades in OME.

**Comment by DellDavidMcKay** [comment]
If I access the direct RESTful API which returns the same result as the playbook, it will work if I specify $skip=0&$top=2000
If I do not set skip=0, I only get the top 50 results from OME. This is under data pagination in the OME RESTful API guide

I did have to change queries to var.json instead of var.device_info but otherwise the direct rest call was fine

**Comment by sachin-apa** [comment]
@DellDavidMcKay Thanks for checking.. i tried here and it seems to be working good, we are paginating the values and fetching all the devices.
Anyways i will create a PR with the changes.

**Comment by tallyoh** [comment]
Thank you for fixing this. I can confirm that the recently released 8.5.0 version does indeed fix the inventory plugin. I am now able to get all results (not just the first 50). Thanks again.
