### ISSUE TITLE
[BUG]: Same warning message but in 2 different states

### ISSUE THREAD

**Issue by Tclemento** [dell/dellemc-openmanage-ansible-modules#552]
### Bug Description

I launch the iDRAC update on a personal catalog. The dirac is already up to date. 
I launched on the 2 hosts who have an idrac card.

I have the same message 'Unable to complete the operation because the catalog name entered has either unsupported firmware packages or same version installed on the server.' But I received this message in two different states: OK and Failed.

Attached the capture:
![playbook](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/34621233/13807665-6dc7-420a-b163-bb39a8484722)

### Component or Module Name

idrac_firmware

### Ansible Version

Ansible 8.3.0

### Python Version

Python 3.9.16

### iDRAC/OME/OME-M version

omsdk               1.2.509
Idrac version (Both hosts) 6.10.80.00

### Operating System

RHEL 9

### Playbook Used

  - name: Update firmware
    dellemc.openmanage.idrac_firmware:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_pass }}"
      validate_certs: False
      ignore_cert_warning: True
      share_name: 'https://{{server_ip}}'
      catalog_file_name: "iDRAC_Catalog.xml"
      apply_update: True
    register: idrac_inventory
    delegate_to: localhost

### Logs

- "A scheduled Update from Repository completed and no applicable updates were found."
- "Unable to complete the operation because the catalog name entered has either unsupported firmware packages or same version installed on the server."

### Steps to Reproduce

Launch the playbook with module idrac_firmware.

### Expected Behavior

It must be a single state (OK or failed but not both)

### Actual Behavior

Two different states: OK and Failed for same message

**Comment by ShivamSh3** [comment]
I tried this scenario in my machine and was not able to reproduce this error. @Tclemento 
![Output](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/127489963/d30b306b-d22a-48a2-b850-69167a1879a4)

Please download the latest version of collections and retry.

**Comment by Tclemento** [comment]
It’s still the same.

I upgraded the collection to version 8.6.0.

**Comment by ShivamSh3** [comment]
I tried on my machine with the latest collection 8.6.0, but I was not able to reproduce the error.

**Comment by sachin-apa** [comment]
@Tclemento We verified it twice and couldn't reproduce this in our system, Please go to [Dell Support](https://www.dell.com/support), enter your Servicetag and then raise a technical support request. You must have an existing and valid warranty on your server before you can raise a SR.
