### ISSUE TITLE
[QUESTION]: iDRAC 8 stating wrong credentials on playbook run

### ISSUE THREAD

**Issue by wetzel-cam** [dell/dellemc-openmanage-ansible-modules#577]
I'm trying to run an Ansible playbook against multiple version of iDRAC. When I run it against an iDRAC 9 host it works without a problem, but when I try to run it against an iDRAC 8 host I get

    "error": {
        "@Message.ExtendedInfo": [
            {
                "Message": "Unable to complete the operation because an invalid username and/or password is entered, and therefore authentication failed.",
                "MessageArgs": [],
                "MessageArgs@odata.count": 0,
                "MessageId": "IDRAC.2.2.SYS415",
                "RelatedProperties": [],
                "RelatedProperties@odata.count": 0,
                "Resolution": "Enter valid user name and password and retry the operation.",
                "Severity": "Warning"
            }
        ],
        "code": "Base.1.5.GeneralError",
        "message": "A general error has occurred. See ExtendedInfo for more information"
    }

I verified that I can login with the given credentials to the Web GUI and that the account has admin permissions.

Is there something I need to activate on the server? It is relatively default settings.

### Edit:

I'm trying to run the idrac_attributes module

**Comment by rajshekarp87** [comment]
Hi @wetzel-cam,
idrac_attributes module works fine with both iDRAC8 and iDRAC9. This error will occur if an invalid username or password is entered. **No need to make any specific settings (activate) on the server.** Can you please share below details.

- Playbook
- iDRAC8 firmware version

Checked on iDRAC8 in our lab. It works fine. Shared below the module output for your reference:

```
changed: [idrac8] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ca_path": null,
            "idrac_attributes": {
                "SNMP.1.AgentCommunity": "test",
                "SNMP.1.AgentEnable": "Enabled",
                "SNMP.1.DiscoveryPort": 163
            },
            "idrac_ip": "xx.xxx.xx.xx",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "username",
            "lifecycle_controller_attributes": null,
            "resource_id": null,
            "system_attributes": null,
            "timeout": 30,
            "validate_certs": false
        }
    },
    "msg": "Successfully updated the attributes."
}

PLAY RECAP ***********************************************************************************************************************************************************
idrac8                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

**Comment by wetzel-cam** [comment]
Thanks for answering @rajshekarp87.

Below is my Playbook setup for trying to get Syslog attributes set:

    - name: "Enable syslog settings for iDRAC 8/7"
      dellemc.openmanage.idrac_attributes: 
        idrac_ip: "{{ hostvars[item].idrac_host }}"    
        idrac_user: "{{ hostvars[item].idrac_user }}"                                         
        idrac_password: "{{ hostvars[item].idrac_pass }}" 
        validate_certs: false
        idrac_attributes:          
          SysLog.1#SysLogEnable: "Enable"  
          SysLog.1#Port: "{{ syslog.port }}" 
          SysLog.1#Server1: "{{ syslog.server1 }}"     
          SysLog.1#Server2: "{{ syslog.server2 }} "   
          SysLog.1#Server3: "{{ syslog.server3 }} "    
        with_items: "{{ hostvars }}"    
        when: hostvars[item].idrac_version in [7, 8]`

There is a inventory file that defines the connection variables needed, and a config file that assigns the values to set them.

The iDRAC I am testing it against is 2.84.84.84.

**Comment by wetzel-cam** [comment]
Unfortunately, I'm just an idiot and was pointing it to the wrong server the whole time...
