### ISSUE TITLE
[QUESTION]: ome_firmware modules simultaneous  limit 

### ISSUE THREAD

**Issue by lovilak** [dell/dellemc-openmanage-ansible-modules#615]
[QUESTION]: Simultaneous openmanage ome_firmware upgrade session 

## ome_firmware number of simultaneous  limitation

- ansible_collections/dellemc/openmanage version 5.0.1
- openmanage Version 4.0.0 (Build 202) 

Hi , 
- Is there a limitation in session number to fire a **ome_firmware** ansible task to update XX hosts  against a baseline ? 
- How to tune this limitation ? 

I have launch a playbook with 30 hosts but it load and create **5 tasks at a time**; which make the playbook beeing very long to execute the all inventory.

Thanks for your help

Regards

**Comment by anupamaloke** [comment]
@lovilak, could you please share the playbook? It is always good to create a static device group in OME, add them to the firmware baseline and then update the firmware for non-compliant devices. From an ansible perspective, it just uses OME REST APIs to submit a firmware update job in OME, and then monitors the job through completion. Firmware Update is a long process, so it might take a while.

**Comment by anupamaloke** [comment]
@lovilak , please let us know whether we can close this request now. Please feel free to open a new request / issue if you are running into an issue.

**Comment by anupamaloke** [comment]
@lovilak, I am closing this issue. Please feel free to open a new issue(s) if you have any questions.
