### ISSUE TITLE
[QUESTION]: Firmware updates on iDRAC 8 

### ISSUE THREAD

**Issue by spear-dev** [dell/dellemc-openmanage-ansible-modules#632]
### How can the team help?
Hi, 
We need to support  Dell R630s, R640s, and R650s. I am using the [`redfish_firmware`](https://galaxy.ansible.com/ui/repo/published/dellemc/openmanage/content/module/redfish_firmware/?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW&version=9.0.0) module for the R640s and R650s (iDRAC 9). Is there a alternative module that I can use for the R630 (iDRAC 8) ?  The other modules seem want a Catalog file, but we just have the .exe file shared VIA an HTTP server.

**Details: ?**

**Comment by anupamaloke** [comment]
@spear-dev, recommendation would be to use the catalog based firmware update as that is the optimum way to update component firmware on iDRAC without worrying about scheduling the updates in required order with minimum server reboots. You can create a firmware repository using [Dell Repository Manager](https://www.dell.com/support/kbdoc/en-us/000177083/support-for-dell-emc-repository-manager-drm). It can be installed on your linux or windows machine and can be used to create a catalog file and repository that you can host on your HTTP web server. Best part is that you don't have to create multiple repository for all your servers (R630, R640 and R650).

If you still want to go via the .exe route, then I guess the only way would be to use the 'racadm' commands with ansible ssh or directly call the WS-Man APIs using ansible.builtin.uri modules (see [iDRAC8 Linux WS-Man Guide](https://downloads.dell.com/solutions/general-solution-resources/White%20Papers/LC_Web_Services_Interface_Guide_Linux.pdf) )

**Comment by spear-dev** [comment]
@anupamaloke thank you for the recommendation. We will try those options out.

**Comment by anupamaloke** [comment]
@spear-dev, please let us know whether we can close this now.

**Comment by anupamaloke** [comment]
@spear-dev, I am closing this issue now. Please feel free to reopen a new issue(s) if you have any questions.
