### ISSUE TITLE
[FEATURE]: ome_application_network_proxy needs Proxy Exclusion List

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#644]
**Describe the solution you'd like**
The existing module `ome_application_network_proxy` needs to support managing the Proxy Exclusion List in the Proxy Configuration

**Describe alternatives you've considered**
Manually setting for now

**Additional context**
![image](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/9374884/37a4369e-12bc-4cea-8380-64986ce5421f)

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by anupamaloke** [comment]
@MallocArray , thank you for submitting this feature request. It is on our backlog and we will prioritize it accordingly over the next releases.

**Comment by rajshekarp87** [comment]
@MallocArray,

ome_application_network_proxy module is enhanced to support the configuration of **Proxy Exclusion list** and **Ignore Certificate Validation**. Kindly use the latest collection
