### ISSUE TITLE
[QUESTION]: Galaxy.yml in Signed Archive

### ISSUE THREAD

**Issue by thebeanogamer** [dell/dellemc-openmanage-ansible-modules#674]
### How can the team help?

I am currently working on packaging up this collection as an RPM in Fedora. Could you please clarify why the `galaxy.yml` is not included in the signed release archive? This isn't a problem, as we can pull that individual file from Git and the rest from the archive, but I don't think it's obvious why it's been done this way.

Thanks for your help!

**Comment by sachin-apa** [comment]
@thebeanogamer we use command `ansible-galaxy collection build` to build the tar and the tool by default excludes few files and `galaxy.yml` is one of it.
Please refer [here](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_distributing.html#include-all-with-explicit-ignores) for more details.

Let us know if any other way we can help.

**Comment by sachin-apa** [comment]
@thebeanogamer Closing this for now.
Please feel free to reopen or create a new if any,
