### ISSUE TITLE
HTTPS firmware update catalog filename extension support

### ISSUE THREAD

**Issue by cwhel** [dell/dellemc-openmanage-ansible-modules#68]
We're using the branch fw_update_url branch to update our idracs via the dell repo directly.  They've recently changed to requiring the use of HTTPS to pull from their repo and utilize the `.cab` file extension now instead of `.xml` or `.xml.gz`.  Is there anyway we can get the module updated to support the new file extension?  Thanks!

**Comment by rajeevarakkal** [comment]
@cwhel we currently support `Catalog.xml ` extension. We will update you once we support .`cab `extension

**Comment by jagadeeshnv** [comment]
@cwhel The module supports .cab extension as well.
