### ISSUE TITLE
[QUESTION]:dellemc.openmanage is slow with an iDRAC8 vs. iDRAC9

### ISSUE THREAD

**Issue by pgitbeta** [dell/dellemc-openmanage-ansible-modules#680]
### How can the team help?

**Details: ?**
Running a simple task to both an idrac8 and 9 in the same playbook (or separated) the iDRAC8 can take 1:47 or longer per task to complete while the iDRAC9 takes seconds to complete an entire playbook. Tried an M630 and R730xd both had updated Bios FW's and using module 9.3.0. 

Can you verify this is with the iDRAC8, or as expected or is there something with my config I should look at?

- name: test openmanage idrac attributes speed
    dellemc.openmanage.idrac_attributes:
      idrac_ip: "{{ baseuri }}"
      idrac_user: "{{ username }}"
      idrac_password: "{{ password }}"
      validate_certs: false
      idrac_attributes:
          SNMP.1.AgentCommunity: Enabled
    delegate_to: localhost

**Comment by sachin-apa** [comment]
@pgitbeta This is expected because idrac9 uses the direct REST API's and is much faster. idrac8 uses SCP feature to update the attributes as the REST API is not available.
Nothing wrong in your config.

**Comment by pgitbeta** [comment]
Thanks for the confirmation!
