### ISSUE TITLE
Set syslog server address and altering config

### ISSUE THREAD

**Issue by sthorsen** [dell/dellemc-openmanage-ansible-modules#689]
**Describe the solution you'd like**
With `dellemc.openmanage.idrac_syslog`  we can Enable syslog. But there are no option to set the server address, port and alerting config

**Describe alternatives you've considered**
As it is now, we have to login to every idrac and set the settings by clicking. That is not fun when having multiple servers

**Additional context**
---

**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rajshekarp87** [comment]
@sthorsen,

You can use the idrac_attributes  (https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/plugins/modules/idrac_attributes.py)  module to configure syslog settings, alerting, or any other attributes. Below is the playbook for configuring syslog settings.

    - name: Configure iDRAC attributes
      dellemc.openmanage.idrac_attributes:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_user }}"
        validate_certs: false
        idrac_attributes:
          SysLog.1.SysLogEnable: Enabled
          SysLog.1.Server1: 1.1.1.1
          SysLog.1.Port: 514

**Comment by sthorsen** [comment]
@rajshekarp87 

Awesome, thank you. I did not think of that. Thank you, works like a charm :)
