### ISSUE TITLE
SecureErase and BOSS

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#707]
Hello 

in recently released 9.5.0 you added
- The idrac_redfish_storage_controller module is enhanced to support secure and/or cryptographic erase of the physical disk.

can you pls confirm that it also works with disks connected to BOSS controller ?
thanks

**Comment by rajshekarp87** [comment]
@markatdxb,

The secure and/or cryptographic erase feature supports the disks connected to the BOSS controller
