### ISSUE TITLE
Idrac_os_deployment 

### ISSUE THREAD

**Issue by lostongoogle** [dell/dellemc-openmanage-ansible-modules#72]
I am attempting to use the new way of remote os deployment. I currently am receiving an error `PLAY [Booting to Network Operating System image] *******************************

TASK [Booting to Network Operating System image] *******************************
fatal: [10.51.0.33]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "boot_to_network_iso() got an unexpected keyword argument 'expose_duration'"}

PLAY RECAP *********************************************************************
10.51.0.33                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

i am not sure why I would be getting that, I know that the expose_duration defaults to 1080, and its not a required argument. so why would that be thrown? 

Thank you!

**Comment by rajeevarakkal** [comment]
@lostongoogle ; this "devel" code is require OMSDK to be updated to the latest devel copy. Kindly ensure that you have the latest omsdk present. Follow the README instructions

Lets know the result

**Comment by lostongoogle** [comment]
i tried uninstalled the omsdk using "pip uninstall omsdk" and then following the steps. 
I am able to install the requirements but when I get to the `sh build.sh 1.2 379` it fails and says 
```
[root@pcl omsdk]# sh build.sh 1.2 379
usage: setup-omdrivers.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup-omdrivers.py --help [cmd1 cmd2 ...]
   or: setup-omdrivers.py --help-commands
   or: setup-omdrivers.py cmd --help

error: invalid command 'bdist_wheel'
usage: setup-omsdk.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup-omsdk.py --help [cmd1 cmd2 ...]
   or: setup-omsdk.py --help-commands
   or: setup-omsdk.py cmd --help

error: invalid command 'bdist_wheel'

I think my issue might be my environment. i have both python 2.7 and python 3.6 installed. pip3 install omsdk works but installs 1.2.370 same with pip install omsdk. any ideas im a little new to this so im a little stuck
```

**Comment by lostongoogle** [comment]
Thanks Rajeevarakkal, that did work. im faced with a different issue at this time. 

> `fatal: [10.51.0.33]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": {"DeleteOnCompletion": "false", "InstanceID": "DCIM_OSDConcreteJob:1", "JobName": "BootToNetworkISO", "JobStatus": "Failed", "Key": "<null_index>", "Message": "Inaccessible network share", "MessageID": "OSD47", "Name": "BootToNetworkISO", "Status": "Failed", "file": "10.51.0.37:/ISOs/VMware-VMvisor-Installer-6.7.0", "retval": false}}`

i receive that error but i am able to mount the share on my machine so I know the share is accessible, any ideas? is there a way to use idrac_os_deployment from a local iso?

**Comment by jagadeeshnv** [comment]
- The idrac is unable to access the network share using the credentials specified or the firewall might be enabled and is preventing access to the share. Make sure that the firewall is disabled, and that the credentials (username, password) are correct. 
- As of now we have no support for local iso

**Comment by lostongoogle** [comment]
just a bit of further clarification. 
both the nfs share, ansible controller, and idrac are all on the same internal network. i have verified that I can mount the nfs share from the nfs server to the ansible controller. my playbook is as follows  `---
-
  connection: local
  gather_facts: false
  hosts: general
  name: Booting to Network Operating System image
  tasks:
    - name: "Booting to Network Operating System image"
      idrac_os_deployment:
        idrac_ip: "10.51.0.33"
        idrac_pwd: "pass"
        idrac_user: "root"
        share_name: "10.51.0.28:/nfsshare"
        share_user: "root"
        share_pwd: "pass"
        iso_image: "VMware-VMvisor-Installer-6.7.0.iso"
`

I dont see where the issue could be as df  -h shows that "10.51.0.28:/nfsshare is mounted on /test" 
and it allows me to traverse the share,read and write to it. any further assistance is greatly appreciated as ive been really struggling to grasp where the errors are coming from.

Thank you

**Comment by lostongoogle** [comment]
i found the issue was my nfs exports, i had it exporting to the ansible controller but not the idrac.
