### ISSUE TITLE
[QUESTION]: IDRAC Firmware via http/https

### ISSUE THREAD

**Issue by eoin0brien** [dell/dellemc-openmanage-ansible-modules#738]
The idrac_firmware.yml file includes tasks to get the firmware from downloads.dell.com, this site has now been retired. Is there any update to this to pull the firmware via a public repo or do we need to store it locally for this module to work?

Thanks

**Comment by anupamaloke** [comment]
@eoin0brien, thank you for bringing this to our notice. We will check internally and update the URL to the alternative URL (if available). The recommendation is to always create your own local repo and host it on a remote share (NFS, CIFS or HTTP/S) as you would not want to expose your iDRACs to external IPs. There are a couple of ways to do it:

- [**Dell Repository Manager (DRM)**](https://www.dell.com/support/home/product-support/product/repository-manager/docs)
- [**Dell OpenManage Enterprise (OME) with Update Manager Plugin (UMP)**]( https://www.dell.com/support/kbdoc/000180518/update-manager-plugin-ump)

Also, **new download location for the latest Catalog file**  is https://dl.dell.com/catalog/catalog.xml.gz

**Comment by anupamaloke** [comment]
Updated the new catalog.xml.gz download link in the previous post. 
With that I am closing this issue. Please feel free to raise another if any further information is needed.
