### ISSUE TITLE
idrac_os_deployment failed with unexpected keyword argument 'expose_duration'

### ISSUE THREAD

**Issue by wioch** [dell/dellemc-openmanage-ansible-modules#75]
Hello, 

I'm trying to automate configuration of Dell servers, including ESXi installation. Here is error I get:
```
[root@host ansible]# ansible-playbook sgw_r740xd_deploy.yml -e 'ansible_python_interpreter=/usr/bin/python3'
(...)
The full traceback is:
  File "/tmp/ansible_idrac_os_deployment_payload_8evj60jv/__main__.py", line 142, in run_boot_to_network_iso
    boot_status = idrac.config_mgr.boot_to_network_iso(share_obj, "", expose_duration=cim_exp_duration)

fatal: [10.20.204.85]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "expose_duration": 180,
            "idrac_ip": "10.20.204.85",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "iso_image": "esxi_iso_6.7u2_sgw987.iso",
            "share_name": "10.20.205.69:/deployment",
            "share_password": null,
            "share_user": null
        }
    },
    "msg": "boot_to_network_iso() got an unexpected keyword argument 'expose_duration'"
```

I'm using ansible role for this. So, Inventory:
```
[sgw_idrac]
10.20.204.85
```

Master .yml file:
```---
- hosts: sgw_idrac
  connection: local
  gather_facts: False
  roles:
    - sgw_r740xd_role
```

Task file:
```---
- name: ESXi installation from prepared ISO image
  idrac_os_deployment:
    idrac_ip: "{{ iDRAC_IP_Address }}"
    idrac_user: "{{ iDRAC_Username }}"
    idrac_password: "{{ iDRAC_Password }}"
    idrac_port: "{{ iDRAC_Port }}"
    share_name: "{{ Server_IP }}:{{ path_to_NFS_share }}"
    iso_image: "esxi_iso_6.7u2_sgw{{ SGW_Number }}.iso"
    expose_duration: 180
```

and variables:
```
---
# Full path to NFS share from which iDRAC will pick up files
path_to_NFS_share: '/deployment'

# Number of SGW
SGW_Number: '987'

# Ansible serer IP address
Server_IP: '10.20.205.69'

# iDRAC Parameters
iDRAC_IP_Address: '10.20.204.85'
iDRAC_Username: 'root'
iDRAC_Password: 'rootpass'
iDRAC_Port: '443'
```

I saw issue #72 that was about the same problem. However, omsdk is installed and NFS exports are fine:
```
[root@host ansible]# pip3 list | grep -i oms
omsdk          1.2.370
[root@host ansible]# cat /etc/exports
/deployment     10.20.205.69(rw,sync) #this is for localhost
/deployment     10.20.204.85(rw,sync) #this is for iDRAC
```

What is more, I'm using the same role for sending SCP files (like NTP settings or user creation) in idrac_server_config_profile module. And that works perfectly. 

Could it be python mixup ? I mean, omsdk is installed using pip3. I start role with additional parameter to use python3, but the idrac_os_deployment module comes from /usr/lib/**python2.7**/site-packages/ansible/modules/remote_management/dellemc/idrac_os_deployment.py ?

Thanks in advance for any tips&hints. 

Regards,
w.

**Comment by rajeevarakkal** [comment]
@wioch ,this "devel" code is require OMSDK to be updated to the latest devel copy. Kindly ensure that you have the latest omsdk present. Follow the README instructions
Lets know the result

**Comment by rajeevarakkal** [comment]
@wioch ; Let us know the update

**Comment by rajeevarakkal** [comment]
Thanks am closing this issue

**Comment by HugoLS** [comment]
Hi,

I've the same issue.
I'm able to get the firmware_inventory (only to test the access to idrac), but i'm not able to boot on network because of "expose_duration" parameter.

[root@ansible esxi]# pip list | grep omsdk
omsdk (1.2.370)
[root@ansible esxi]# ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

**Comment by rajeevarakkal** [comment]
@HigoLS, this "devel" code is require OMSDK to be updated to the latest devel copy. Kindly ensure that you have the latest omsdk present. Follow the README instructions
Lets know the result

I am reopening this defect for tracking

**Comment by HugoLS** [comment]
Hi Rajeevarakkal,

It solved the issue, thank you.
Pip was not able to find the latest version, so i followed instructions in OMSDK Readme. Clone the git, then install it manually. I have now the version 387

```
[root@ansible dist]# pip list | grep omsdk
omsdk (1.2.387-)
```

**Comment by rajeevarakkal** [comment]
great 👍  Actually pip omsdk is compatible with master copy of OMAM. Hence we have updated readme instructions for "devel" copy on how to get latest OMSDK.

Closing this issue
