### ISSUE TITLE
ome_device_info - detailed_inventory - error

### ISSUE THREAD

**Issue by mpunix** [dell/dellemc-openmanage-ansible-modules#80]
Hi,
Need help on the ome_device_info module where it failing to fetch the inventory.  Error message "Failed to fetch the device information". 

I am getting mixed inventory results for the blades on the same Chassis. Failing one is similar configuration and completes the Discovery/Inventory from the OME. From the Modular I can see the Blade information. 

No issues on the credentials, I can run the "dellemc_get_system_inventory" to query the idrac on the failed one with "ome_device_info". 

Environment: OME --> Modular (PowerEdge MX7000) --> Blade (MX740c).

Error message:
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_subset": "detailed_inventory",
            "hostname": "ome.dns.local",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "system_query_options": {
                "device_id": null,
                "device_service_tag": [
                    "G12345"
                ],
                "filter": null,
                "inventory_type": "deviceManagement"
            },
            "username": "omeuser"
        }
    },
    "msg": "Failed to fetch the device information"
}

**Comment by rajeevarakkal** [comment]
@mpunix it could be possible that OME is unable to cater this particular device information back to ome_device_info module at that particular point of time. Are still facing the same issue?

**Comment by mpunix** [comment]
@rajeevarakkal  - Yes, we did a fresh install of OME 3.3 and did the discovery. Initially it was working for a two days and starting failing again. Failure is more random on the devices in the MX group.

**Comment by rajeevarakkal** [comment]
@mpunix Since the failure intermittent and first couple of days module was returning proper inventory; looks like we have to look into device refresh has some issues on MX device OME. Give us some time to get back to you

**Comment by rajeevarakkal** [comment]
@mpunix  We are working on this; will revert back to you soon

**Comment by mpunix** [comment]
@rajeevarakkal  - thank you for the update

**Comment by rajeevarakkal** [comment]
@mpunix; please share us the playbook you are executing

**Comment by mpunix** [comment]
@rajeevarakkal  - sent you an email, we have Dell Service request relate to this issue.  you may refer the details. Sorry if it is anything duplicated.

**Comment by jagadeeshnv** [comment]
Issue Fixed in v2.0.6

**Comment by mpunix** [comment]
thank you.
