### ISSUE TITLE
Storing inventory in a variable and to a file

### ISSUE THREAD

**Issue by cheppalli** [dell/dellemc-openmanage-ansible-modules#81]

**Comment by cheppalli** [comment]
How to store the Firmware inventory to a variable or file in nice format? I can only see when i use verbose

**Comment by anupamaloke** [comment]
@cheppalli, you can register the output of the firmware inventory task in a variable that you can access later in your playbook.

```
  tasks:
  - name: Get Installed Firmware Inventory
    dellemc_get_firmware_inventory:
      idrac_ip:  "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
    register: firmware_inventory

  - debug:
      var: firmware_inventory
```

I will be closing this issue.

**Comment by cheppalli** [comment]
can I get it in the form of csv or ini format? component=version type. The output is hard to read

**Comment by anupamaloke** [comment]
@cheppalli, you can use the [jq](https://stedolan.github.io/jq/) to accomplish something like this.  Following thread has some good information on generating csv out of the JSON output using 'jq':
https://github.com/dell/redfish-ansible-module/issues/35
