### ISSUE TITLE
About firmware updating with playbook "idrac_firmware"

### ISSUE THREAD

**Issue by Kdy77k** [dell/dellemc-openmanage-ansible-modules#83]
Hi,
I have two issues:
1. I use playbook "idrac_firmware" to update idrac 9's firmware with parameter "repo_share_name" http://downloads.dell.com/Catalog" and share_name "catalog.xml" with error code 40X
I find that there is catalog.xml.gz not catalog.xml within the url. how to walk round it?
2. I also want to update firmware with specific one (not search from official website).
I use playbook "dellemc_ome_firmware_with_job_tracking.yml" to update with specific firmware. But playbook also return 40X error code? Why and how to fix it?
Thanks!

**Comment by rajeevarakkal** [comment]
@Kdy77k; currently we support Catalog.xml; we will check the feasibility to support Catalog.xml.gz

Regarding `dellecm_ome_fimware` module issue, share us the exact playbook inputs

**Comment by Kdy77k** [comment]
> @Kdy77k; currently we support Catalog.xml; we will check the feasibility to support Catalog.xml.gz
> 
> Regarding `dellecm_ome_fimware` module issue, share us the exact playbook inputs

Hi,
How to update firmware with binary file name directly?

**Comment by rajeevarakkal** [comment]
@Kdy77k  We are working on this. You can except an feature support in couple of weeks

**Comment by rajeevarakkal** [comment]
@Kdy77k you can update the firmware from a HTTP location or local directory using "redfish_firmware" module.

**Comment by rajeevarakkal** [comment]
@Kdy77k closing this defect now.
