### ISSUE TITLE
idrac_firmware module update from single EXE file

### ISSUE THREAD

**Issue by tsquillario** [dell/dellemc-openmanage-ansible-modules#84]
One scenario that I see my customers try to do again and again is they want to update from a single file EXE. There is no way to do this in Ansible currently. 

You can do this via racadm currently from an NFS share. `racadm update -f BIOS_F7R7C_WN64_1.9.3.EXE -l 192.168.1.100:/mnt/data/drm`

This can be done via Redfish as well. It may be valuable to have 2 implementations, one via Redfish and one via OMSDK for backwards compatibility especially when customers need to update to iDRAC firmware x.x.x.x to even start using Redfish.

**Comment by rajeevarakkal** [comment]
@tsquillario We are working on this. You can except an feature support in month or two

**Comment by rajeevarakkal** [comment]
@tsquillario you can update the firmware from a HTTP location or local directory using "redfish_firmware" module.

**Comment by tsquillario** [comment]
Perfect! I will test it out and create a new issue if it doesn't work as expected. I like that the redfish_ modules don't use the omsdk
