### ISSUE TITLE
Unsupported Reset Type:GracefulRestart

### ISSUE THREAD

**Issue by alxlcr** [dell/dellemc-openmanage-ansible-modules#91]
Hi there, I just upgraded the IDRAC to 2.70.70.70 on some R630 servers and now the dellemc_change_power_state gets me the "Unsupported Reset Type:GracefulRestart" message. Is anyone else seeing this?

**Comment by alxlcr** [comment]
as a workaround, I added logic to do a graceful shutdown and power back on, pls see below if anyone finds it useful:

- name: First, try restart the server to make sure any pending jobs are completed; any error here will be addressed next
  delegate_to: localhost
  dellemc_change_power_state:
    idrac_ip:          "{{ansible_host}}"
    idrac_user:        "{{ansible_user}}"
    idrac_pwd:         "{{ansible_password}}"
    change_power:      "GracefulRestart"
  register: serveractionResult
  ignore_errors: True
###### the following 3 tasks were added to compensate for lack of GracefulRestart compatibility in idrac 2.70.70.70
- name: Graceful shutdown if the restart failed
  delegate_to: localhost
  dellemc_change_power_state:
    idrac_ip:          "{{ansible_host}}"
    idrac_user:        "{{ansible_user}}"
    idrac_pwd:         "{{ansible_password}}"
    change_power:      "GracefulShutdown"
  when: (serveractionResult is failed)
- name: Wait for the server to be powered off
  delegate_to: localhost
  command: "sshpass -p {{ansible_password}} ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{ansible_user}}@{{ansible_host}} racadm serveraction powerstatus"
  async: 300
  poll: 10
  register: result
  retries: 30
  delay: 10
  until: ("OFF" in (result.stdout| replace('\n', '')))
  when: (serveractionResult is failed)
- name: Power back on if the restart failed
  delegate_to: localhost
  dellemc_change_power_state:
    idrac_ip:          "{{ansible_host}}"
    idrac_user:        "{{ansible_user}}"
    idrac_pwd:         "{{ansible_password}}"
    change_power: "On"
  when: (serveractionResult is failed)

**Comment by rajeevarakkal** [comment]
@alxlcr We will check this and get back to you

**Comment by rajeevarakkal** [comment]
This is fixed in the latest "devel"
