### ISSUE TITLE
Questions to different modules - smtp, syslog and ip vs dns

### ISSUE THREAD

**Issue by thizmo** [dell/dellemc-openmanage-ansible-modules#98]
Dear all,

thx a lot for that great work! 
I managed to configure a bunch of new 14G idracs in less then one hour.

Yet i have some questions regarding different modules
a) SMTP
- in the idrac9 webinterface you can have a DNS instead of IP for SMTP-Server. Not yet with the ansible module. I would need to set a DNS there for my SMTP-server.
- I need to set a sender mail-adress as well as the target adress. Is this somehow possible?

b) Syslog
- Only can activate syslog regarding to the module/doc. Yet i didn't found a way to set the syslog ip/dns

c) Alerting
- I managed to activate the alerts. Yet is there a way to explicitly getting the system to tell what type of alerts it should report? 
- What would it report if you just enable the alerts with ansible?

If i am missing something please point me in the right direction. Also if there is another way like with redfish or ome (which i don't have any experience with, yet.)

Thx

**Comment by rajeevarakkal** [comment]
@thizmo Its great that OMAM modules helped you in configurating the server within an hour.  Thanks :)

The missing points you have pointed out, lets have a look and get back to you

**Comment by dids50x** [comment]
Hello,

I have exactly the same needs as @thizmo .

Please Dell (@rajeevarakkal ), could you make the changes available soon?

Regards.

**Comment by aminastireanu** [comment]
Hi,
I have stumbled upon the same limitations of the ansible module: - unable to set fqdn for smtp server or set sender address (these can be done from iDRAC9 v 4.20.20.20 for eg.)

If it's not on the roadmap any time soon could anyone share with us the redfish API path for this? I couldn't find it myself in [this API guide](https://dl.dell.com/topicspdf/idrac9-lifecycle-controller-v4x-series_api-guide_en-us.pdf) 

Thanks,
