### ISSUE TITLE
unexpected keyword argument 'expose_duration'

### ISSUE THREAD

**Issue by shelkro** [dell/dellemc-openmanage-ansible-modules#99]
Running ansible playbook with idrac_os_deployment returns    "msg": "boot_to_network_iso() got an unexpected keyword argument 'expose_duration'".

The latest OMSDK is installed. 
bash-4.4# pip3 freeze | grep omsdk
omsdk==1.2.387
bash-4.4# python --version
Python 3.6.8

This playbook is working correctly on another ansible system with python 2.7.
bash-4.2# pip freeze | grep omsdk
omsdk===1.2.387-
bash-4.2# python --version
Python 2.7.5

Thank you.

**Comment by rajeevarakkal** [comment]
@shelkro , Can you try pointing to right python environment or reinstalling omsdk latest "devel" copy. Looks like omsdk is not reflecting the changes or in a different python environment.

**Comment by jagadeeshnv** [comment]
@shelkro could you install the devel copy from omsdk. That has the required update

**Comment by jagadeeshnv** [comment]
@shelkro it has been fixed if you get the latest devel from omsdk and OMAM
